// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::SystemUnitOfWorkFactoryTrait;
use crate::system::dtos::{CreateSystemDto, SystemDto};
use anyhow::{Ok, Result};

pub struct CreateOrphansSystemMultiUseCase {
    uow_factory: Box<dyn SystemUnitOfWorkFactoryTrait>,
}

impl CreateOrphansSystemMultiUseCase {
    pub fn new(uow_factory: Box<dyn SystemUnitOfWorkFactoryTrait>) -> Self {
        CreateOrphansSystemMultiUseCase { uow_factory }
    }
    pub fn execute(&mut self, dtos: &[CreateSystemDto]) -> Result<Vec<SystemDto>> {
        // create
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entities =
            uow.create_system_multi(&dtos.iter().map(|dto| dto.into()).collect::<Vec<_>>())?;
        uow.commit()?;

        Ok(entities.into_iter().map(|entity| entity.into()).collect())
    }
}
