// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::SystemUnitOfWorkROFactoryTrait;
use crate::system::dtos::SystemDto;
use anyhow::Result;
use common::types::EntityId;

pub struct GetSystemUseCase {
    uow_factory: Box<dyn SystemUnitOfWorkROFactoryTrait>,
}

impl GetSystemUseCase {
    pub fn new(uow_factory: Box<dyn SystemUnitOfWorkROFactoryTrait>) -> Self {
        GetSystemUseCase { uow_factory }
    }

    pub fn execute(&self, id: &EntityId) -> Result<Option<SystemDto>> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entity_option = uow.get_system(&id)?;
        uow.end_transaction()?;

        Ok(entity_option.map(|entity| entity.into()))
    }
}
