// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::SystemUnitOfWorkFactoryTrait;
use crate::system::dtos::SystemDto;
use anyhow::{Ok, Result};

pub struct UpdateSystemUseCase {
    uow_factory: Box<dyn SystemUnitOfWorkFactoryTrait>,
}

impl UpdateSystemUseCase {
    pub fn new(uow_factory: Box<dyn SystemUnitOfWorkFactoryTrait>) -> Self {
        UpdateSystemUseCase { uow_factory }
    }

    pub fn description(&self) -> &str {
        "Update System"
    }

    pub fn execute(&mut self, dto: &SystemDto) -> Result<SystemDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        // check if id exists
        if uow.get_system(&dto.id)?.is_none() {
            return Err(anyhow::anyhow!("System with id {} does not exist", dto.id));
        }

        let entity = uow.update_system(&dto.into())?;
        uow.commit()?;

        Ok(entity.into())
    }
}
