#pragma once

#include <QtCore/QtGlobal>

#if defined(SIMPLEEXAMPLE_CONTROLLER_LIBRARY)
#define SIMPLEEXAMPLE_CONTROLLER_EXPORT Q_DECL_EXPORT
#else // if defined(SIMPLEEXAMPLE_CONTROLLER_LIBRARY)
#define SIMPLEEXAMPLE_CONTROLLER_EXPORT Q_DECL_IMPORT
#endif // if defined(SIMPLEEXAMPLE_CONTROLLER_LIBRARY)
