// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use common::entities::Root;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RootDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub cars: Vec<EntityId>,
    pub customers: Vec<EntityId>,
}

impl From<RootDto> for Root {
    fn from(dto: RootDto) -> Self {
        Root {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            cars: dto.cars,
            customers: dto.customers,
        }
    }
}

impl From<&RootDto> for Root {
    fn from(dto: &RootDto) -> Self {
        Root {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            cars: dto.cars.clone(),
            customers: dto.customers.clone(),
        }
    }
}

impl From<Root> for RootDto {
    fn from(entity: Root) -> Self {
        RootDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            cars: entity.cars,
            customers: entity.customers,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateRootDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub cars: Vec<EntityId>,
    pub customers: Vec<EntityId>,
}

impl From<CreateRootDto> for Root {
    fn from(dto: CreateRootDto) -> Self {
        Root {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            cars: dto.cars,
            customers: dto.customers,
        }
    }
}

impl From<&CreateRootDto> for Root {
    fn from(dto: &CreateRootDto) -> Self {
        Root {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            cars: dto.cars.clone(),
            customers: dto.customers.clone(),
        }
    }
}

impl From<Root> for CreateRootDto {
    fn from(entity: Root) -> Self {
        CreateRootDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            cars: entity.cars,
            customers: entity.customers,
        }
    }
}

pub use common::direct_access::root::RootRelationshipField;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RootRelationshipDto {
    pub id: EntityId,
    pub field: RootRelationshipField,
    pub right_ids: Vec<EntityId>,
}
