// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::dto_repository::DtoRelationshipField;
use super::dto_repository::DtoTable;
use super::dto_repository::DtoTableRO;
use crate::database::Bincode;
use crate::database::db_helpers;
use crate::entities::Dto;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{Error, ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const DTO_TABLE: TableDefinition<EntityId, Bincode<Dto>> = TableDefinition::new("dto");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

const DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("dto_field_from_dto_fields_junction");
// backward relationships

const DTO_FROM_USE_CASE_DTO_IN_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("dto_from_use_case_dto_in_junction");
const DTO_FROM_USE_CASE_DTO_OUT_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("dto_from_use_case_dto_out_junction");
fn get_junction_table_definition(
    field: &'_ DtoRelationshipField,
) -> TableDefinition<'_, EntityId, Vec<EntityId>> {
    match field {
        DtoRelationshipField::Fields => DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE,
    }
}

pub struct DtoRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> DtoRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        DtoRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), Error> {
        transaction.open_table(DTO_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        transaction.open_table(DTO_FROM_USE_CASE_DTO_IN_JUNCTION_TABLE)?;
        transaction.open_table(DTO_FROM_USE_CASE_DTO_OUT_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> DtoTable for DtoRedbTable<'a> {
    fn create(&mut self, entity: &Dto) -> Result<Dto, Error> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Dto>, Error> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Dto) -> Result<Dto, Error> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn delete(&mut self, id: &EntityId) -> Result<(), Error> {
        self.delete_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[Dto]) -> Result<Vec<Dto>, Error> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"dto".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut dto_table = self.transaction.open_table(DTO_TABLE)?;

        let mut fields_junction_table = self
            .transaction
            .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Dto {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if dto_table.get(&entity.id)?.is_some() {
                    return Err(Error::TableDoesNotExist(
                        format!("UseCase id {} already in use", &entity.id).to_string(),
                    ));
                }
                entity.clone()
            };
            Dto {
                id: counter,
                ..entity.clone()
            };

            dto_table.insert(new_entity.id, new_entity.clone())?;

            fields_junction_table.insert(new_entity.id, new_entity.fields.clone())?;
            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("dto".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Dto>>, Error> {
        let mut list = Vec::new();
        let dto_table = self.transaction.open_table(DTO_TABLE)?;

        let fields_junction_table = self
            .transaction
            .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        if ids.is_empty() {
            let mut iter = dto_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                // get fields from junction table
                let fetched_fields = fields_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.fields = fetched_fields;

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = dto_table.get(id)? {
                    let mut entity = guard.value().clone();

                    // get fields from junction table
                    let fetched_fields = fields_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default();
                    entity.fields = fetched_fields;
                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn update_multi(&mut self, entities: &[Dto]) -> Result<Vec<Dto>, Error> {
        let mut updated = Vec::new();
        let mut dto_table = self.transaction.open_table(DTO_TABLE)?;

        let mut fields_junction_table = self
            .transaction
            .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        for entity in entities {
            dto_table.insert(entity.id, entity)?;

            fields_junction_table.insert(entity.id, entity.fields.clone())?;
            updated.push(entity.clone());
        }
        Ok(updated)
    }

    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error> {
        let mut dto_table = self.transaction.open_table(DTO_TABLE)?;

        // forward relationships

        let mut fields_junction_table = self
            .transaction
            .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        // backward relationships

        let mut backward_use_case_dto_in_junction_table = self
            .transaction
            .open_table(DTO_FROM_USE_CASE_DTO_IN_JUNCTION_TABLE)?;
        let mut backward_use_case_dto_out_junction_table = self
            .transaction
            .open_table(DTO_FROM_USE_CASE_DTO_OUT_JUNCTION_TABLE)?;

        for id in ids {
            dto_table.remove(id)?;

            fields_junction_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_use_case_dto_in_junction_table,
                id,
            )?;
            db_helpers::delete_from_backward_junction_table(
                &mut backward_use_case_dto_out_junction_table,
                id,
            )?;
        }
        Ok(())
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &DtoRelationshipField,
    ) -> Result<Vec<EntityId>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &DtoRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }

    fn set_relationship_multi(
        &mut self,
        field: &DtoRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), Error> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        for (left_id, entities) in relationships {
            table.insert(left_id, entities)?;
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &DtoRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), Error> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, right_ids.to_vec())?;
        Ok(())
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, Error> {
        let dto_table = self.transaction.open_table(DTO_TABLE)?;

        // Snapshot entity rows as bincode bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = dto_table.get(id)? {
                let entity = guard.value();
                let bytes = bincode::serialize(&entity).map_err(|e| {
                    Error::TableDoesNotExist(format!("bincode serialize error: {}", e))
                })?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
let mut forward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            for id in ids {
                if let Some(guard) = junction_table.get(id)? {
                    entries.push((*id, guard.value().clone()));
                }
            }
            forward_junctions.push(JunctionSnapshot {
                table_name: "dto_field_from_dto_fields_junction".to_string(),
                entries,
            });
        }

        // Snapshot backward junction tables (entries that reference any of the given ids)
let mut backward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(DTO_FROM_USE_CASE_DTO_IN_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "dto_from_use_case_dto_in_junction".to_string(),
                    entries,
                });
            }
        }
        {
            let junction_table = self
                .transaction
                .open_table(DTO_FROM_USE_CASE_DTO_OUT_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "dto_from_use_case_dto_out_junction".to_string(),
                    entries,
                });
            }
        }

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "dto".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), Error> {
        let mut dto_table = self.transaction.open_table(DTO_TABLE)?;

        // Restore entity rows from bincode bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: Dto = bincode::deserialize(bytes).map_err(|e| {
                Error::TableDoesNotExist(format!("bincode deserialize error: {}", e))
            })?;
            dto_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;
            for junction_snap in &snap.forward_junctions {
                if junction_snap.table_name == "dto_field_from_dto_fields_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        // Restore backward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(DTO_FROM_USE_CASE_DTO_IN_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "dto_from_use_case_dto_in_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }
        {
            let mut junction_table = self
                .transaction
                .open_table(DTO_FROM_USE_CASE_DTO_OUT_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "dto_from_use_case_dto_out_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        Ok(())
    }
}

pub struct DtoRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> DtoRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        DtoRedbTableRO { transaction }
    }
}

impl<'a> DtoTableRO for DtoRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Dto>, Error> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Dto>>, Error> {
        let mut list = Vec::new();
        let dto_table = self.transaction.open_table(DTO_TABLE)?;

        let fields_junction_table = self
            .transaction
            .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        if ids.is_empty() {
            let mut iter = dto_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                // get fields from junction table
                let fetched_fields = fields_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default();
                entity.fields = fetched_fields;

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = dto_table.get(id)? {
                    let mut entity = guard.value().clone();

                    // get fields from junction table
                    let fetched_fields = fields_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default();
                    entity.fields = fetched_fields;
                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &DtoRelationshipField,
    ) -> Result<Vec<EntityId>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &DtoRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }
}
