// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::units_of_work::FeatureUnitOfWorkFactory;
use super::{
    dtos::{CreateFeatureDto, FeatureDto},
    units_of_work::FeatureUnitOfWorkROFactory,
    use_cases::{
        create_feature_multi_uc::CreateFeatureMultiUseCase,
        create_feature_uc::CreateFeatureUseCase,
        create_orphans_feature_multi_uc::CreateOrphansFeatureMultiUseCase,
        create_orphans_feature_uc::CreateOrphansFeatureUseCase,
        get_feature_multi_uc::GetFeatureMultiUseCase, get_feature_uc::GetFeatureUseCase,
        remove_feature_multi_uc::RemoveFeatureMultiUseCase,
        remove_feature_uc::RemoveFeatureUseCase,
        update_feature_multi_uc::UpdateFeatureMultiUseCase,
        update_feature_uc::UpdateFeatureUseCase,
    },
};
use crate::FeatureRelationshipDto;
use crate::feature::use_cases::get_feature_relationship_uc::GetFeatureRelationshipUseCase;
use crate::feature::use_cases::set_feature_relationship_uc::SetFeatureRelationshipUseCase;
use anyhow::{Ok, Result};
use common::direct_access::feature::FeatureRelationshipField;
use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphans(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateFeatureDto,
) -> Result<FeatureDto> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateOrphansFeatureUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity.clone())?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}
pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateFeatureDto,
    owner_id: EntityId,
    index: i32,
) -> Result<FeatureDto> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateFeatureUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity.clone(), owner_id, index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}
pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<FeatureDto>> {
    let uow_factory = FeatureUnitOfWorkROFactory::new(db_context);
    let uc = GetFeatureUseCase::new(Box::new(uow_factory));
    uc.execute(id)
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &FeatureDto,
) -> Result<FeatureDto> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = UpdateFeatureUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn remove(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<()> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = RemoveFeatureUseCase::new(Box::new(uow_factory));
    uc.execute(id)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn create_orphans_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateFeatureDto],
) -> Result<Vec<FeatureDto>> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateOrphansFeatureMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}
pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateFeatureDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<FeatureDto>> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateFeatureMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities, owner_id, index)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}
pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<FeatureDto>>> {
    let uow_factory = FeatureUnitOfWorkROFactory::new(db_context);
    let uc = GetFeatureMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[FeatureDto],
) -> Result<Vec<FeatureDto>> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = UpdateFeatureMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = RemoveFeatureMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn get_relationship(
    db_context: &DbContext,
    id: &EntityId,
    field: &FeatureRelationshipField,
) -> Result<Vec<EntityId>> {
    let uow_factory = FeatureUnitOfWorkROFactory::new(db_context);
    let uc = GetFeatureRelationshipUseCase::new(Box::new(uow_factory));
    uc.execute(id, field)
}

pub fn set_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &FeatureRelationshipDto,
) -> Result<()> {
    let uow_factory = FeatureUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = SetFeatureRelationshipUseCase::new(Box::new(uow_factory));
    uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}
