// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::units_of_work::UseCaseUnitOfWorkFactory;
use super::{
    dtos::{CreateUseCaseDto, UseCaseDto},
    units_of_work::UseCaseUnitOfWorkROFactory,
    use_cases::{
        create_use_case_multi_uc::CreateUseCaseMultiUseCase,
        create_use_case_uc::CreateUseCaseUseCase, get_use_case_multi_uc::GetUseCaseMultiUseCase,
        get_use_case_uc::GetUseCaseUseCase, remove_use_case_multi_uc::RemoveUseCaseMultiUseCase,
        remove_use_case_uc::RemoveUseCaseUseCase,
        update_use_case_multi_uc::UpdateUseCaseMultiUseCase,
        update_use_case_uc::UpdateUseCaseUseCase,
    },
};
use anyhow::{Ok, Result};

use crate::UseCaseRelationshipDto;
use crate::use_case::use_cases::get_use_case_relationship_uc::GetUseCaseRelationshipUseCase;
use crate::use_case::use_cases::set_use_case_relationship_uc::SetUseCaseRelationshipUseCase;
use common::direct_access::use_case::UseCaseRelationshipField;

use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateUseCaseDto,
) -> Result<UseCaseDto> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateUseCaseUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity.clone())?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<UseCaseDto>> {
    let uow_factory = UseCaseUnitOfWorkROFactory::new(db_context);
    let uc = GetUseCaseUseCase::new(Box::new(uow_factory));
    uc.execute(id)
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &UseCaseDto,
) -> Result<UseCaseDto> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = UpdateUseCaseUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn remove(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<()> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = RemoveUseCaseUseCase::new(Box::new(uow_factory));
    uc.execute(id)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateUseCaseDto],
) -> Result<Vec<UseCaseDto>> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateUseCaseMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<UseCaseDto>>> {
    let uow_factory = UseCaseUnitOfWorkROFactory::new(db_context);
    let uc = GetUseCaseMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[UseCaseDto],
) -> Result<Vec<UseCaseDto>> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = UpdateUseCaseMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = RemoveUseCaseMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn get_relationship(
    db_context: &DbContext,
    id: &EntityId,
    field: &UseCaseRelationshipField,
) -> Result<Vec<EntityId>> {
    let uow_factory = UseCaseUnitOfWorkROFactory::new(db_context);
    let uc = GetUseCaseRelationshipUseCase::new(Box::new(uow_factory));
    uc.execute(id, field)
}

pub fn set_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    dto: &UseCaseRelationshipDto,
) -> Result<()> {
    let uow_factory = UseCaseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = SetUseCaseRelationshipUseCase::new(Box::new(uow_factory));
    uc.execute(dto)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}
