// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::DtoUnitOfWorkROFactoryTrait;
use crate::dto::dtos::DtoDto;
use anyhow::Result;
use common::types::EntityId;

pub struct GetDtoMultiUseCase {
    uow_factory: Box<dyn DtoUnitOfWorkROFactoryTrait>,
}

impl GetDtoMultiUseCase {
    pub fn new(uow_factory: Box<dyn DtoUnitOfWorkROFactoryTrait>) -> Self {
        GetDtoMultiUseCase { uow_factory }
    }

    pub fn execute(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoDto>>> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entities = uow.get_dto_multi(ids)?;
        uow.end_transaction()?;
        Ok(entities
            .into_iter()
            .map(|entity| entity.map(|r| r.into()))
            .collect())
    }
}
