// Generated by Qleany v0.0.1 from entity_controller.tera

use super::{
    dtos::{CreateRootDto, RootDto},
    units_of_work::{RootReadUoWFactory, RootWriteUoWFactory},
};
use crate::RootRelationshipDto;
use anyhow::{Ok, Result};
use common::direct_access::root::RootRelationshipField;
use common::direct_access::use_cases;

use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphan(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateRootDto,
) -> Result<RootDto> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let entity_in: common::entities::Root = entity.into();
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn create_orphan_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateRootDto],
) -> Result<Vec<RootDto>> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Root> = entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<RootDto>> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute(id)?.map(|e| e.into()))
}

pub fn get_all(db_context: &DbContext) -> Result<Vec<RootDto>> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute_all()?.into_iter().map(|e| e.into()).collect())
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<RootDto>>> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc
        .execute_multi(ids)?
        .into_iter()
        .map(|o| o.map(|e| e.into()))
        .collect())
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &RootDto,
) -> Result<RootDto> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::Root = entity.into();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[RootDto],
) -> Result<Vec<RootDto>> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::Root> = entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn remove(db_context: &DbContext, event_hub: &Arc<EventHub>, id: &EntityId) -> Result<()> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute(id)?;
    Ok(())
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute_multi(ids)?;
    Ok(())
}

pub fn get_relationship(
    db_context: &DbContext,
    id: &EntityId,
    field: &RootRelationshipField,
) -> Result<Vec<EntityId>> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipUseCase::<RootRelationshipField, _>::new(uow_factory);
    uc.execute(id, field)
}

pub fn get_relationship_many(
    db_context: &DbContext,
    ids: &[EntityId],
    field: &RootRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipManyUseCase::<RootRelationshipField, _>::new(uow_factory);
    uc.execute(ids, field)
}

pub fn get_relationship_count(
    db_context: &DbContext,
    id: &EntityId,
    field: &RootRelationshipField,
) -> Result<usize> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipCountUseCase::<RootRelationshipField, _>::new(uow_factory);
    uc.execute(id, field)
}

pub fn get_relationship_in_range(
    db_context: &DbContext,
    id: &EntityId,
    field: &RootRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    let uow_factory = RootReadUoWFactory::new(db_context);
    let uc = use_cases::GetRelationshipInRangeUseCase::<RootRelationshipField, _>::new(uow_factory);
    uc.execute(id, field, offset, limit)
}

pub fn set_relationship(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &RootRelationshipDto,
) -> Result<()> {
    let uow_factory = RootWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::SetRelationshipUseCase::<RootRelationshipField, _>::new(uow_factory);
    uc.execute(&dto.id, &dto.field, dto.right_ids.as_slice())?;
    Ok(())
}
