// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::car_repository::CarRelationshipField;
use super::car_repository::CarTable;
use super::car_repository::CarTableRO;
use crate::database::db_helpers;
use crate::database::Bincode;
use crate::entities::Car;
use crate::types::EntityId;
use redb::{Error, ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const CAR_TABLE: TableDefinition<EntityId, Bincode<Car>> = TableDefinition::new("car");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

// backward relationships

const CAR_FROM_ROOT_CARS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("car_from_root_cars_junction");

pub struct CarRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> CarRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        CarRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), Error> {
        transaction.open_table(CAR_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(CAR_FROM_ROOT_CARS_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> CarTable for CarRedbTable<'a> {
    fn create(&mut self, entity: &Car) -> Result<Car, Error> {
        let v = self.create_multi(&[entity.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Car>, Error> {
        let v = self.get_multi(&[id.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Car) -> Result<Car, Error> {
        let v = self.update_multi(&[entity.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }
    fn delete(&mut self, id: &EntityId) -> Result<(), Error> {
        self.delete_multi(&[id.clone()])
    }

    fn create_multi(&mut self, entities: &[Car]) -> Result<Vec<Car>, Error> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"car".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut car_table = self.transaction.open_table(CAR_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Car {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if car_table.get(&entity.id)?.is_some() {
                    return Err(Error::TableDoesNotExist(
                        format!("UseCase id {} already in use", &entity.id).to_string(),
                    ));
                }
                entity.clone()
            };

            car_table.insert(new_entity.id, new_entity.clone())?;

            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("car".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Car>>, Error> {
        let mut list = Vec::new();
        let car_table = self.transaction.open_table(CAR_TABLE)?;

        if ids.is_empty() {
            let mut iter = car_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = car_table.get(id)? {
                    let mut entity = guard.value().clone();

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn update_multi(&mut self, entities: &[Car]) -> Result<Vec<Car>, Error> {
        let mut updated = Vec::new();
        let mut car_table = self.transaction.open_table(CAR_TABLE)?;

        for entity in entities {
            car_table.insert(entity.id, entity)?;

            updated.push(entity.clone());
        }
        Ok(updated)
    }

    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error> {
        let mut car_table = self.transaction.open_table(CAR_TABLE)?;

        // forward relationships

        // backward relationships

        let mut backward_root_cars_junction_table = self
            .transaction
            .open_table(CAR_FROM_ROOT_CARS_JUNCTION_TABLE)?;

        for id in ids {
            car_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_root_cars_junction_table,
                id,
            )?;
        }
        Ok(())
    }
}

pub struct CarRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> CarRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        CarRedbTableRO { transaction }
    }
}

impl<'a> CarTableRO for CarRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Car>, Error> {
        let v = self.get_multi(&[id.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Car>>, Error> {
        let mut list = Vec::new();
        let car_table = self.transaction.open_table(CAR_TABLE)?;

        if ids.is_empty() {
            let mut iter = car_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = car_table.get(id)? {
                    let mut entity = guard.value().clone();

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }
}
