// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::GlobalUnitOfWorkROFactoryTrait;
use crate::global::dtos::GlobalDto;
use anyhow::Result;
use common::types::EntityId;

pub struct GetGlobalMultiUseCase {
    uow_factory: Box<dyn GlobalUnitOfWorkROFactoryTrait>,
}

impl GetGlobalMultiUseCase {
    pub fn new(uow_factory: Box<dyn GlobalUnitOfWorkROFactoryTrait>) -> Self {
        GetGlobalMultiUseCase { uow_factory }
    }

    pub fn execute(&self, ids: &[EntityId]) -> Result<Vec<Option<GlobalDto>>> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entities = uow.get_global_multi(ids)?;
        uow.end_transaction()?;
        Ok(entities
            .into_iter()
            .map(|entity| entity.map(|r| r.into()))
            .collect())
    }
}
