// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::GlobalUnitOfWorkROFactoryTrait;
use crate::global::dtos::GlobalDto;
use anyhow::Result;

pub struct GetAllGlobalUseCase {
    uow_factory: Box<dyn GlobalUnitOfWorkROFactoryTrait>,
}

impl GetAllGlobalUseCase {
    pub fn new(uow_factory: Box<dyn GlobalUnitOfWorkROFactoryTrait>) -> Self {
        GetAllGlobalUseCase { uow_factory }
    }

    pub fn execute(&self) -> Result<Vec<GlobalDto>> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entities = uow.get_all_global()?;
        uow.end_transaction()?;
        Ok(entities.into_iter().map(|entity| entity.into()).collect())
    }
}
