// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::FileUnitOfWorkFactoryTrait;
use crate::file::dtos::{CreateFileDto, FileDto};
use anyhow::{Ok, Result};
use common::types::EntityId;

pub struct CreateFileMultiUseCase {
    uow_factory: Box<dyn FileUnitOfWorkFactoryTrait>,
}

impl CreateFileMultiUseCase {
    pub fn new(uow_factory: Box<dyn FileUnitOfWorkFactoryTrait>) -> Self {
        CreateFileMultiUseCase { uow_factory }
    }

    pub fn execute(
        &mut self,
        dtos: &[CreateFileDto],
        owner_id: EntityId,
        index: i32,
    ) -> Result<Vec<FileDto>> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Create with owner (repository handles junction management internally)
        let entities = uow.create_file_multi_with_owner(
            &dtos.iter().map(|dto| dto.into()).collect::<Vec<_>>(),
            owner_id,
            index,
        )?;

        uow.commit()?;

        Ok(entities.into_iter().map(|entity| entity.into()).collect())
    }
}
