// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::FileUnitOfWorkFactoryTrait;
use crate::file::dtos::FileDto;
use anyhow::{Ok, Result};

pub struct UpdateFileMultiUseCase {
    uow_factory: Box<dyn FileUnitOfWorkFactoryTrait>,
}

impl UpdateFileMultiUseCase {
    pub fn new(uow_factory: Box<dyn FileUnitOfWorkFactoryTrait>) -> Self {
        UpdateFileMultiUseCase { uow_factory }
    }

    pub fn execute(&mut self, dtos: &[FileDto]) -> Result<Vec<FileDto>> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // check if id exists
        let mut exists = true;
        for FileDto { id, .. } in dtos {
            if uow.get_file(id)?.is_none() {
                exists = false;
                break;
            }
        }
        if !exists {
            return Err(anyhow::anyhow!("One or more ids do not exist"));
        }

        let entities =
            uow.update_file_multi(&dtos.iter().map(|dto| dto.into()).collect::<Vec<_>>())?;
        uow.commit()?;

        Ok(entities.into_iter().map(|entity| entity.into()).collect())
    }
}
