// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::RootUnitOfWorkFactoryTrait;
use crate::root::dtos::{CreateRootDto, RootDto};
use anyhow::{Ok, Result};

pub struct CreateOrphansRootUseCase {
    uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>,
}

impl CreateOrphansRootUseCase {
    pub fn new(uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>) -> Self {
        CreateOrphansRootUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: CreateRootDto) -> Result<RootDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entity = uow.create_root(&dto.into())?;
        uow.commit()?;

        Ok(entity.into())
    }
}
