// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::RootUnitOfWorkFactoryTrait;
use anyhow::{Ok, Result};
use common::types::EntityId;

/// Use case to remove a root entity.
pub struct RemoveRootUseCase {
    uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>,
}

impl RemoveRootUseCase {
    pub fn new(uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>) -> Self {
        RemoveRootUseCase { uow_factory }
    }

    pub fn execute(&mut self, id: &EntityId) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        // check if id exists
        if uow.get_root(id)?.is_none() {
            return Err(anyhow::anyhow!("Root with id {} does not exist", id));
        }
        uow.delete_root(id)?;
        uow.commit()?;

        Ok(())
    }
}
