// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::RootUnitOfWorkFactoryTrait;
use anyhow::{Ok, Result};
use common::types::EntityId;

/// Use case to remove multiple root entities.
pub struct RemoveRootMultiUseCase {
    uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>,
}

impl RemoveRootMultiUseCase {
    pub fn new(uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>) -> Self {
        RemoveRootMultiUseCase { uow_factory }
    }

    pub fn execute(&mut self, ids: &[EntityId]) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        // check if all ids exist
        for id in ids {
            if uow.get_root(id)?.is_none() {
                return Err(anyhow::anyhow!("Root with id {} does not exist", id));
            }
        }
        uow.delete_root_multi(ids)?;
        uow.commit()?;

        Ok(())
    }
}
