// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::RootUnitOfWorkFactoryTrait;
use crate::root::dtos::RootDto;
use anyhow::{Ok, Result};

pub struct UpdateRootMultiUseCase {
    uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>,
}

impl UpdateRootMultiUseCase {
    pub fn new(uow_factory: Box<dyn RootUnitOfWorkFactoryTrait>) -> Self {
        UpdateRootMultiUseCase { uow_factory }
    }

    pub fn execute(&mut self, dtos: &[RootDto]) -> Result<Vec<RootDto>> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // check if id exists
        let mut exists = true;
        for RootDto { id, .. } in dtos {
            if uow.get_root(id)?.is_none() {
                exists = false;
                break;
            }
        }
        if !exists {
            return Err(anyhow::anyhow!("One or more ids do not exist"));
        }

        let entities =
            uow.update_root_multi(&dtos.iter().map(|dto| dto.into()).collect::<Vec<_>>())?;
        uow.commit()?;

        Ok(entities.into_iter().map(|entity| entity.into()).collect())
    }
}
