// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

pub mod entity_repository;
pub(super) mod entity_table;
pub use entity_repository::EntityRelationshipField;
