// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.



use super::UserInterfaceUnitOfWorkROFactoryTrait;
use crate::user_interface::dtos::UserInterfaceDto;
use anyhow::Result;
use common::types::EntityId;

pub struct GetUserInterfaceMultiUseCase {
    uow_factory: Box<dyn UserInterfaceUnitOfWorkROFactoryTrait>,
}

impl GetUserInterfaceMultiUseCase {
    pub fn new(uow_factory: Box<dyn UserInterfaceUnitOfWorkROFactoryTrait>) -> Self {
        GetUserInterfaceMultiUseCase { uow_factory }
    }

    pub fn execute(&self, ids: &[EntityId]) -> Result<Vec<Option<UserInterfaceDto>>> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entities = uow.get_user_interface_multi(ids)?;
        uow.end_transaction()?;
        Ok(entities
            .into_iter()
            .map(|entity| entity.map(|r| r.into()))
            .collect())
    }
}

