// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.



use super::UserInterfaceUnitOfWorkFactoryTrait;
use crate::user_interface::dtos::UserInterfaceDto;
use anyhow::{Ok, Result};
use common::{entities::UserInterface, undo_redo::UndoRedoCommand};
use std::any::Any;
use std::collections::VecDeque;

pub struct UpdateUserInterfaceUseCase {
    uow_factory: Box<dyn UserInterfaceUnitOfWorkFactoryTrait>,
    undo_stack: VecDeque<UserInterface>,
    redo_stack: VecDeque<UserInterface>,
}

impl UpdateUserInterfaceUseCase {
    pub fn new(uow_factory: Box<dyn UserInterfaceUnitOfWorkFactoryTrait>) -> Self {
        UpdateUserInterfaceUseCase {
            uow_factory,
            undo_stack: VecDeque::new(),
            redo_stack: VecDeque::new(),
        }
    }

    pub fn description(&self) -> &str {
        "Update UserInterface"
    }

    pub fn execute(&mut self, dto: &UserInterfaceDto) -> Result<UserInterfaceDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        // check if id exists
        if uow.get_user_interface(&dto.id)?.is_none() {
            return Err(anyhow::anyhow!("UserInterface with id {} does not exist", dto.id));
        }
        // store in undo stack
        let entity = uow.get_user_interface(&dto.id)?.unwrap();
        self.undo_stack.push_back(entity.clone());

        let entity = uow.update_user_interface(&dto.into())?;
        uow.commit()?;

        Ok(entity.into())
    }
}

impl UndoRedoCommand for UpdateUserInterfaceUseCase {
    fn undo(&mut self) -> Result<()> {
        if let Some(last_entity) = self.undo_stack.pop_back() {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            uow.update_user_interface(&last_entity)?;
            uow.commit()?;
            self.redo_stack.push_back(last_entity);
        }
        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        if let Some(entity) = self.redo_stack.pop_back() {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            uow.update_user_interface(&entity)?;
            uow.commit()?;
            self.undo_stack.push_back(entity);
        }
        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}

