// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.
use crate::AddCustomerDto;
use crate::AddCustomerReturnDto;
use anyhow::{anyhow, Result};
use common::database::CommandUnitOfWork;
use common::entities::{Customer, Root};
use common::types::EntityId;

pub trait AddCustomerUnitOfWorkFactoryTrait {
    fn create(&self) -> Box<dyn AddCustomerUnitOfWorkTrait>;
}
#[macros::uow_action(entity = "Root", action = "Get")]
#[macros::uow_action(entity = "Root", action = "GetMulti")]
#[macros::uow_action(entity = "Customer", action = "Get")]
#[macros::uow_action(entity = "Customer", action = "GetMulti")]
pub trait AddCustomerUnitOfWorkTrait: CommandUnitOfWork {}

pub struct AddCustomerUseCase {
    uow_factory: Box<dyn AddCustomerUnitOfWorkFactoryTrait>,
}

impl AddCustomerUseCase {
    pub fn new(uow_factory: Box<dyn AddCustomerUnitOfWorkFactoryTrait>) -> Self {
        AddCustomerUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &AddCustomerDto) -> Result<AddCustomerReturnDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: AddCustomerUseCase to be implemented
        unimplemented!("AddCustomerUseCase unimplemented");
        uow.commit()?;
        //Ok(AddCustomerReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for CreateGlobalUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: AddCustomerUseCase  undo to be implemented
        unimplemented!("AddCustomerUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: AddCustomerUseCase  redo to be implemented
        unimplemented!("AddCustomerUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
