// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

// Sub-modules for UserInterface use cases
pub(super) mod create_orphan_user_interface_multi_uc;
pub(super) mod create_orphan_user_interface_uc;
pub(super) mod create_user_interface_multi_uc;
pub(super) mod create_user_interface_uc;
pub(super) mod get_all_user_interface_uc;
pub(super) mod get_user_interface_multi_uc;
pub(super) mod get_user_interface_uc;
pub(super) mod remove_user_interface_multi_uc;
pub(super) mod remove_user_interface_uc;
pub(super) mod update_user_interface_multi_uc;
pub(super) mod update_user_interface_uc;

use anyhow::Result;
use common::database::{CommandUnitOfWork, QueryUnitOfWork};
use common::entities::UserInterface;
use common::types::EntityId;

pub(in crate::user_interface) trait UserInterfaceUnitOfWorkFactoryTrait:
    Send + Sync
{
    fn create(&self) -> Box<dyn UserInterfaceUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "UserInterface", action = "CreateOrphan")]
#[macros::uow_action(entity = "UserInterface", action = "CreateOrphanMulti")]
#[macros::uow_action(entity = "UserInterface", action = "Create")]
#[macros::uow_action(entity = "UserInterface", action = "CreateMulti")]
#[macros::uow_action(entity = "UserInterface", action = "Get")]
#[macros::uow_action(entity = "UserInterface", action = "GetMulti")]
#[macros::uow_action(entity = "UserInterface", action = "GetAll")]
#[macros::uow_action(entity = "UserInterface", action = "Update")]
#[macros::uow_action(entity = "UserInterface", action = "UpdateMulti")]
#[macros::uow_action(entity = "UserInterface", action = "Delete")]
#[macros::uow_action(entity = "UserInterface", action = "DeleteMulti")]
#[macros::uow_action(entity = "UserInterface", action = "Snapshot")]
#[macros::uow_action(entity = "UserInterface", action = "Restore")]
pub(in crate::user_interface) trait UserInterfaceUnitOfWorkTrait:
    CommandUnitOfWork
{
    fn get_relationships_from_owner(&self, owner_id: &EntityId) -> Result<Vec<EntityId>>;
    fn set_relationships_in_owner(&self, owner_id: &EntityId, ids: &[EntityId]) -> Result<()>;
}

pub(in crate::user_interface) trait UserInterfaceUnitOfWorkROFactoryTrait {
    fn create(&self) -> Box<dyn UserInterfaceUnitOfWorkROTrait>;
}

#[macros::uow_action(entity = "UserInterface", action = "GetRO")]
#[macros::uow_action(entity = "UserInterface", action = "GetMultiRO")]
#[macros::uow_action(entity = "UserInterface", action = "GetAllRO")]
pub(in crate::user_interface) trait UserInterfaceUnitOfWorkROTrait:
    QueryUnitOfWork
{
}
