// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::units_of_work::UserInterfaceUnitOfWorkFactory;
use super::{
    dtos::{CreateUserInterfaceDto, UserInterfaceDto},
    units_of_work::UserInterfaceUnitOfWorkROFactory,
    use_cases::{
        create_user_interface_multi_uc::CreateUserInterfaceMultiUseCase,
        create_user_interface_uc::CreateUserInterfaceUseCase,
        get_user_interface_multi_uc::GetUserInterfaceMultiUseCase,
        get_user_interface_uc::GetUserInterfaceUseCase,
        remove_user_interface_multi_uc::RemoveUserInterfaceMultiUseCase,
        remove_user_interface_uc::RemoveUserInterfaceUseCase,
        update_user_interface_multi_uc::UpdateUserInterfaceMultiUseCase,
        update_user_interface_uc::UpdateUserInterfaceUseCase,
    },
};
use anyhow::{Ok, Result};

use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &CreateUserInterfaceDto,
) -> Result<UserInterfaceDto> {
    let uow_factory = UserInterfaceUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateUserInterfaceUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity.clone())?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<UserInterfaceDto>> {
    let uow_factory = UserInterfaceUnitOfWorkROFactory::new(db_context);
    let uc = GetUserInterfaceUseCase::new(Box::new(uow_factory));
    uc.execute(id)
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entity: &UserInterfaceDto,
) -> Result<UserInterfaceDto> {
    let uow_factory = UserInterfaceUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = UpdateUserInterfaceUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn remove(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<()> {
    let uow_factory = UserInterfaceUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = RemoveUserInterfaceUseCase::new(Box::new(uow_factory));
    uc.execute(id)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[CreateUserInterfaceDto],
) -> Result<Vec<UserInterfaceDto>> {
    let uow_factory = UserInterfaceUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateUserInterfaceMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn get_multi(
    db_context: &DbContext,
    ids: &[EntityId],
) -> Result<Vec<Option<UserInterfaceDto>>> {
    let uow_factory = UserInterfaceUnitOfWorkROFactory::new(db_context);
    let uc = GetUserInterfaceMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    entities: &[UserInterfaceDto],
) -> Result<Vec<UserInterfaceDto>> {
    let uow_factory = UserInterfaceUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = UpdateUserInterfaceMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(result)
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = UserInterfaceUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = RemoveUserInterfaceMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)?;
    undo_redo_manager.add_command_to_stack(Box::new(uc), stack_id)?;
    Ok(())
}
