// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.
use crate::GenerateCppQtPromptDto;
use crate::GenerateCppQtPromptReturnDto;
use anyhow::{Result, anyhow};
use common::entities::{FileStatus};
use common::entities::{
    Entity, System, Feature, Field, File, Global, Relationship, Root, UseCase, UserInterface,
};
use common::types::EntityId;
use crate::use_cases::common::cpp_qt_code_generator::{generate_code_with_snapshot, GenerationReadOps, SnapshotBuilder};

pub trait GenerateCppQtPromptUnitOfWorkFactoryTrait {
    fn create(&self) -> Box<dyn GenerateCppQtPromptUnitOfWorkTrait>;
}

// Code UoW must provide at least the read-ops required by snapshot builder
pub trait GenerateCppQtPromptUnitOfWorkTrait: GenerationReadOps {}

pub struct GenerateCppQtPromptUseCase {
    uow_factory: Box<dyn GenerateCppQtPromptUnitOfWorkFactoryTrait>,
}

impl GenerateCppQtPromptUseCase {
    pub fn new(uow_factory: Box<dyn GenerateCppQtPromptUnitOfWorkFactoryTrait>) -> Self {
        GenerateCppQtPromptUseCase { uow_factory }
    }

    pub fn execute(
        &mut self,
        dto: &GenerateCppQtPromptDto,
    ) -> Result<GenerateCppQtPromptReturnDto> {

        let timestamp = chrono::Utc::now();

        // create a File

        let file: File = if dto.context {
            File {
                id: 0,
                name: "use_case_prompt".to_string(),
                template_name: "use_case_prompt.tera".to_string(),
                generated_code: None,
                status: FileStatus::Unknown,
                feature: dto.feature_id,
                use_case: dto.use_case_id,
                ..Default::default()
            }
        }
        else {
            File {
                id: 0,
                name: "context".to_string(),
                template_name: "context.tera".to_string(),
                generated_code: None,
                status: FileStatus::Unknown,
                ..Default::default()
            }
        };

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;


        // Build a snapshot for the file
        let uow_ref: &dyn GenerationReadOps = &*uow;
        let (snapshot, _from_cache) = SnapshotBuilder::for_file(uow_ref, &file, &Vec::new())?;

        let prompt_text = generate_code_with_snapshot(&snapshot)?;

        // remove File


        uow.end_transaction()?;



        Ok(GenerateCppQtPromptReturnDto {
            prompt_text
        })
    }
}
