// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use crate::use_cases::common::cpp_qt_code_generator::GenerationOps;
use crate::use_cases::fill_code_in_cpp_qt_files_uc::{
    FillCodeInCppQtFilesUnitOfWorkFactoryTrait, FillCodeInCppQtFilesUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::CommandUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
use common::entities::Dto;
use common::entities::DtoField;
use common::entities::Entity;
use common::entities::Feature;
use common::entities::Field;
use common::entities::File;
use common::entities::Global;
use common::entities::Relationship;
use common::entities::Root;
use common::entities::System;
use common::entities::UseCase;
use common::entities::UserInterface;
use common::entities::Workspace;
use common::event::{AllEvent, DirectAccessEntity, Event, EventBuffer, EventHub, Origin};
use common::types;
use common::types::EntityId;
use std::sync::Arc;
use std::sync::Mutex;

pub struct FillCodeInCppQtFilesUnitOfWork {
    context: DbContext,
    transaction: Mutex<Option<Transaction>>,
    event_hub: Arc<EventHub>,
    event_buffer: Mutex<EventBuffer>,
}

impl FillCodeInCppQtFilesUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        FillCodeInCppQtFilesUnitOfWork {
            context: db_context.clone(),
            transaction: Mutex::new(None),
            event_hub: event_hub.clone(),
            event_buffer: Mutex::new(EventBuffer::new()),
        }
    }
}

impl CommandUnitOfWork for FillCodeInCppQtFilesUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        *transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        self.event_buffer.lock().unwrap().begin_buffering();
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction.take().unwrap().commit()?;
        drop(transaction); // release lock before flushing events
        for event in self.event_buffer.lock().unwrap().flush() {
            self.event_hub.send_event(event);
        }
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction.take().unwrap().rollback()?;
        drop(transaction);
        self.event_buffer.lock().unwrap().discard();
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        let transaction = self.transaction.lock().unwrap();
        transaction.as_ref().unwrap().create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction_guard = self.transaction.lock().unwrap();
        let mut transaction = transaction_guard.take().unwrap();
        transaction.restore_to_savepoint(savepoint)?;

        // Discard buffered events — savepoint restore invalidated them
        self.event_buffer.lock().unwrap().discard();

        // Send Reset immediately (not buffered — UI must refresh now)
        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        *transaction_guard = Some(transaction);

        Ok(())
    }
}

#[macros::uow_action(entity = "System", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Restore", thread_safe = true)]
impl FillCodeInCppQtFilesUnitOfWorkTrait for FillCodeInCppQtFilesUnitOfWork {}

#[macros::uow_action(entity = "Root", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Root", action = "GetAll", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Workspace", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Workspace", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "UserInterface", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Global", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Feature", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Feature", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "UseCase", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "UseCase", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Dto", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "DtoField", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Entity", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Entity", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Field", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "Relationship", action = "GetMulti", thread_safe = true)]
impl GenerationOps for FillCodeInCppQtFilesUnitOfWork {}

pub struct FillCodeInCppQtFilesUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl FillCodeInCppQtFilesUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        FillCodeInCppQtFilesUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl FillCodeInCppQtFilesUnitOfWorkFactoryTrait for FillCodeInCppQtFilesUnitOfWorkFactory {
    fn create(&self) -> Box<dyn FillCodeInCppQtFilesUnitOfWorkTrait> {
        Box::new(FillCodeInCppQtFilesUnitOfWork::new(
            &self.context,
            &self.event_hub,
        ))
    }
}
