// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use crate::use_cases::fill_code_in_cpp_qt_files_uc::{
    FillCodeInCppQtFilesUnitOfWorkFactoryTrait, FillCodeInCppQtFilesUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::CommandUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
use common::entities::{File, System};
use common::event::{AllEvent, DirectAccessEntity, Event, EventBuffer, EventHub, Origin};
use common::types;
use common::types::EntityId;
use std::sync::Arc;
use std::sync::Mutex;

pub struct FillCodeInCppQtFilesUnitOfWork {
    context: DbContext,
    transaction: Mutex<Option<Transaction>>,
    event_hub: Arc<EventHub>,
    event_buffer: Mutex<EventBuffer>,
}

impl FillCodeInCppQtFilesUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        FillCodeInCppQtFilesUnitOfWork {
            context: db_context.clone(),
            transaction: Mutex::new(None),
            event_hub: event_hub.clone(),
            event_buffer: Mutex::new(EventBuffer::new()),
        }
    }
}

impl CommandUnitOfWork for FillCodeInCppQtFilesUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        *transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        self.event_buffer.lock().unwrap().begin_buffering();
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction.take().unwrap().commit()?;
        drop(transaction); // release lock before flushing events
        for event in self.event_buffer.lock().unwrap().flush() {
            self.event_hub.send_event(event);
        }
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction.take().unwrap().rollback()?;
        drop(transaction);
        self.event_buffer.lock().unwrap().discard();
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        let transaction = self.transaction.lock().unwrap();
        transaction.as_ref().unwrap().create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction_guard = self.transaction.lock().unwrap();
        let mut transaction = transaction_guard.take().unwrap();
        transaction.restore_to_savepoint(savepoint)?;

        // Discard buffered events — savepoint restore invalidated them
        self.event_buffer.lock().unwrap().discard();

        // Send Reset immediately (not buffered — UI must refresh now)
        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        *transaction_guard = Some(transaction);

        Ok(())
    }
}
//TODO: adapt entities and actions to real use : Create, CreateMulti, Get, GetMulti, Update, UpdateMulti, Delete,
//DeleteMulti, GetRO, GetMultiRO, GetRelationship, GetRelationshipRO, GetRelationshipsFromRightIds,
//GetRelationshipsFromRightIdsRO, SetRelationship, SetRelationshipMulti
//
// You have here a long operation read-write unit of work.
//
// RO means Read Only, so *RO actions should not used be here.
// Don't forget to set thread_safe = true for long operation's unit of work.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/fill_code_in_cpp_qt_files_uc.rs
//
#[macros::uow_action(entity = "System", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "System", action = "Restore", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "GetMulti", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Snapshot", thread_safe = true)]
#[macros::uow_action(entity = "File", action = "Restore", thread_safe = true)]
impl FillCodeInCppQtFilesUnitOfWorkTrait for FillCodeInCppQtFilesUnitOfWork {}

pub struct FillCodeInCppQtFilesUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl FillCodeInCppQtFilesUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        FillCodeInCppQtFilesUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl FillCodeInCppQtFilesUnitOfWorkFactoryTrait for FillCodeInCppQtFilesUnitOfWorkFactory {
    fn create(&self) -> Box<dyn FillCodeInCppQtFilesUnitOfWorkTrait> {
        Box::new(FillCodeInCppQtFilesUnitOfWork::new(
            &self.context,
            &self.event_hub,
        ))
    }
}
