// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::RelationshipUnitOfWorkFactoryTrait;
use anyhow::{Ok, Result};
use common::{snapshot::EntityTreeSnapshot, types::EntityId, undo_redo::UndoRedoCommand};
use std::any::Any;

/// Use case to remove multiple relationship entities.
/// Supports undo/redo via entity tree snapshots.
pub struct RemoveRelationshipMultiUseCase {
    uow_factory: Box<dyn RelationshipUnitOfWorkFactoryTrait>,
    entity_tree_snapshot: Option<EntityTreeSnapshot>,
    original_ids: Option<Vec<EntityId>>,
}

impl RemoveRelationshipMultiUseCase {
    pub fn new(uow_factory: Box<dyn RelationshipUnitOfWorkFactoryTrait>) -> Self {
        RemoveRelationshipMultiUseCase {
            uow_factory,
            entity_tree_snapshot: None,
            original_ids: None,
        }
    }

    pub fn execute(&mut self, ids: &[EntityId]) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        // check if all ids exist
        for id in ids {
            if uow.get_relationship(id)?.is_none() {
                return Err(anyhow::anyhow!(
                    "Relationship with id {} does not exist",
                    id
                ));
            }
        }
        // snapshot the entity trees before deletion (for undo)
        self.entity_tree_snapshot = Some(uow.snapshot_relationship(ids)?);
        uow.delete_relationship_multi(ids)?;
        uow.commit()?;
        self.original_ids = Some(ids.to_vec());

        Ok(())
    }
}
impl UndoRedoCommand for RemoveRelationshipMultiUseCase {
    fn undo(&mut self) -> Result<()> {
        if let Some(ref snap) = self.entity_tree_snapshot {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            uow.restore_relationship(snap)?;
            uow.commit()?;
        }
        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        if let Some(ref ids) = self.original_ids {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            // re-snapshot before re-deleting
            self.entity_tree_snapshot = Some(uow.snapshot_relationship(ids)?);
            uow.delete_relationship_multi(ids)?;
            uow.commit()?;
        }
        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
