// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::{
    dtos::{CreateFileDto, FileDto},
    units_of_work::{FileReadUoWFactory, FileWriteUoWFactory},
};
use anyhow::{Ok, Result};
use common::direct_access::use_cases;

use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create_orphan(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateFileDto,
) -> Result<FileDto> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let entity_in: common::entities::File = entity.into();
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn create_orphan_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateFileDto],
) -> Result<Vec<FileDto>> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::File> = entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateOrphanUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &CreateFileDto,
    owner_id: EntityId,
    index: i32,
) -> Result<FileDto> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::File = entity.into();
    let mut uc = use_cases::CreateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in, owner_id, index)?;
    Ok(result.into())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[CreateFileDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<FileDto>> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::File> = entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::CreateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in, owner_id, index)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<FileDto>> {
    let uow_factory = FileReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute(id)?.map(|e| e.into()))
}

pub fn get_all(db_context: &DbContext) -> Result<Vec<FileDto>> {
    let uow_factory = FileReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc.execute_all()?.into_iter().map(|e| e.into()).collect())
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<FileDto>>> {
    let uow_factory = FileReadUoWFactory::new(db_context);
    let uc = use_cases::GetUseCase::new(uow_factory);
    Ok(uc
        .execute_multi(ids)?
        .into_iter()
        .map(|o| o.map(|e| e.into()))
        .collect())
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entity: &FileDto,
) -> Result<FileDto> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let entity_in: common::entities::File = entity.into();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute(&entity_in)?;
    Ok(result.into())
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    entities: &[FileDto],
) -> Result<Vec<FileDto>> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let entities_in: Vec<common::entities::File> = entities.iter().map(|dto| dto.into()).collect();
    let mut uc = use_cases::UpdateUseCase::new(uow_factory);
    let result = uc.execute_multi(&entities_in)?;
    Ok(result.into_iter().map(|e| e.into()).collect())
}

pub fn remove(db_context: &DbContext, event_hub: &Arc<EventHub>, id: &EntityId) -> Result<()> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute(id)?;
    Ok(())
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = FileWriteUoWFactory::new(db_context, event_hub);
    let mut uc = use_cases::RemoveUseCase::new(uow_factory);
    uc.execute_multi(ids)?;
    Ok(())
}
