// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.
use crate::GenerateRustPromptDto;
use crate::GenerateRustPromptReturnDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::types::EntityId;

pub trait GenerateRustPromptUnitOfWorkFactoryTrait {
    fn create(&self) -> Box<dyn GenerateRustPromptUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationship, GetRelationshipRO,
// GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work trait.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/generate_rust_prompt_uow.rs
//
pub trait GenerateRustPromptUnitOfWorkTrait: QueryUnitOfWork {}

pub struct GenerateRustPromptUseCase {
    uow_factory: Box<dyn GenerateRustPromptUnitOfWorkFactoryTrait>,
}

impl GenerateRustPromptUseCase {
    pub fn new(uow_factory: Box<dyn GenerateRustPromptUnitOfWorkFactoryTrait>) -> Self {
        GenerateRustPromptUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &GenerateRustPromptDto) -> Result<GenerateRustPromptReturnDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: GenerateRustPromptUseCase to be implemented
        unimplemented!("GenerateRustPromptUseCase unimplemented");
        uow.end_transaction()?;
        //Ok(GenerateRustPromptReturnDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
