// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use crate::FillRustFilesReturnDto;
use crate::GenerateRustCodeDto;
use crate::GenerateRustCodeReturnDto;
use crate::GenerateRustFilesDto;
use crate::GenerateRustFilesReturnDto;
use crate::units_of_work::fill_code_in_rust_files_uow::FillCodeInRustFilesUnitOfWorkFactory;
use crate::units_of_work::fill_rust_files_uow::FillRustFilesUnitOfWorkFactory;
use crate::units_of_work::generate_rust_code_uow::GenerateRustCodeUnitOfWorkFactory;
use crate::units_of_work::generate_rust_files_uow::GenerateRustFilesUnitOfWorkFactory;
use crate::use_cases::fill_code_in_rust_files_uc::FillCodeInRustFilesUseCase;
use crate::use_cases::fill_rust_files_uc::FillRustFilesUseCase;
use crate::use_cases::generate_rust_code_uc::GenerateRustCodeUseCase;
use crate::use_cases::generate_rust_files_uc::GenerateRustFilesUseCase;
use crate::{FillRustFilesDto, GenerateRustPromptDto, GenerateRustPromptReturnDto};
use anyhow::Result;
use common::event::{Event, Origin};

use common::event::RustFileGenerationEvent::FillRustFiles;
use common::event::RustFileGenerationEvent::GenerateRustCode;
use common::event::RustFileGenerationEvent::GenerateRustPrompt;

use crate::units_of_work::generate_rust_prompt_uow::GenerateRustPromptUnitOfWorkFactory;
use crate::use_cases::generate_rust_prompt_uc::GenerateRustPromptUseCase;
use common::long_operation::{LongOperationManager, OperationProgress};
use common::{database::db_context::DbContext, event::EventHub};
use std::sync::Arc;

pub fn generate_rust_code(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &GenerateRustCodeDto,
) -> Result<GenerateRustCodeReturnDto> {
    let uow_context = GenerateRustCodeUnitOfWorkFactory::new(db_context);
    let uc = GenerateRustCodeUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::RustFileGeneration(GenerateRustCode),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn generate_rust_files(
    db_context: &DbContext,
    _event_hub: &Arc<EventHub>,
    long_operation_manager: &mut LongOperationManager,
    dto: &GenerateRustFilesDto,
) -> Result<String> {
    let uow_context = GenerateRustFilesUnitOfWorkFactory::new(db_context);
    let uc = GenerateRustFilesUseCase::new(Box::new(uow_context), dto);
    let operation_id = long_operation_manager.start_operation(uc);
    Ok(operation_id)
}

pub fn get_generate_rust_files_progress(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Option<OperationProgress> {
    long_operation_manager.get_operation_progress(operation_id)
}

pub fn get_generate_rust_files_result(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Result<Option<GenerateRustFilesReturnDto>> {
    // Get the operation result as a JSON string
    let result_json = long_operation_manager.get_operation_result(operation_id);

    // If there's no result, return None
    if result_json.is_none() {
        return Ok(None);
    }
    // Parse the JSON string into a GenerateRustFilesReturnDto
    let result_dto: GenerateRustFilesReturnDto = serde_json::from_str(&result_json.unwrap())?;

    Ok(Some(result_dto))
}

pub fn fill_rust_files(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &FillRustFilesDto,
) -> Result<FillRustFilesReturnDto> {
    let uow_context = FillRustFilesUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = FillRustFilesUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::RustFileGeneration(FillRustFiles),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}

pub fn fill_code_in_rust_files(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    long_operation_manager: &mut LongOperationManager,
) -> Result<String> {
    let uow_context = FillCodeInRustFilesUnitOfWorkFactory::new(db_context, event_hub);
    let uc = FillCodeInRustFilesUseCase::new(Box::new(uow_context));
    let operation_id = long_operation_manager.start_operation(uc);
    Ok(operation_id)
}

pub fn get_fill_code_in_rust_files_progress(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Option<OperationProgress> {
    long_operation_manager.get_operation_progress(operation_id)
}

pub fn get_fill_code_in_rust_files_result(
    long_operation_manager: &LongOperationManager,
    operation_id: &str,
) -> Result<Option<()>> {
    // Get the operation result as a JSON string
    let result_json = long_operation_manager.get_operation_result(operation_id);

    // If there's no result, return None
    if result_json.is_none() {
        return Ok(None);
    }
    Ok(Some(()))
}

pub fn generate_rust_prompt(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &GenerateRustPromptDto,
) -> Result<GenerateRustPromptReturnDto> {
    let uow_context = GenerateRustPromptUnitOfWorkFactory::new(db_context);
    let mut uc = GenerateRustPromptUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    // Notify that the handling manifest has been loaded
    event_hub.send_event(Event {
        origin: Origin::RustFileGeneration(GenerateRustPrompt),
        ids: vec![],
        data: None,
    });
    Ok(return_dto)
}
