// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::field_repository::FieldRelationshipField;
use super::field_repository::FieldTable;
use super::field_repository::FieldTableRO;
use crate::database::Bincode;
use crate::database::db_helpers;
use crate::entities::Field;
use crate::types::EntityId;
use redb::{Error, ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const FIELD_TABLE: TableDefinition<EntityId, Bincode<Field>> = TableDefinition::new("field");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

const ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("entity_from_field_entity_junction");
// backward relationships

const FIELD_FROM_ENTITY_FIELDS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("field_from_entity_fields_junction");

fn get_junction_table_definition(
    field: &FieldRelationshipField,
) -> TableDefinition<EntityId, Vec<EntityId>> {
    match field {
        FieldRelationshipField::Entity => ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE,
    }
}

pub struct FieldRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> FieldRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        FieldRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), Error> {
        transaction.open_table(FIELD_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE)?;

        transaction.open_table(FIELD_FROM_ENTITY_FIELDS_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> FieldTable for FieldRedbTable<'a> {
    fn create(&mut self, entity: &Field) -> Result<Field, Error> {
        let v = self.create_multi(&[entity.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Field>, Error> {
        let v = self.get_multi(&[id.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Field) -> Result<Field, Error> {
        let v = self.update_multi(&[entity.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }
    fn delete(&mut self, id: &EntityId) -> Result<(), Error> {
        self.delete_multi(&[id.clone()])
    }

    fn create_multi(&mut self, entities: &[Field]) -> Result<Vec<Field>, Error> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"field".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut field_table = self.transaction.open_table(FIELD_TABLE)?;

        let mut entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Field {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if field_table.get(&entity.id)?.is_some() {
                    return Err(Error::TableDoesNotExist(
                        format!("UseCase id {} already in use", &entity.id).to_string(),
                    ));
                }
                entity.clone()
            };

            field_table.insert(new_entity.id, new_entity.clone())?;

            entity_junction_table.insert(
                new_entity.id,
                new_entity
                    .entity
                    .clone()
                    .into_iter()
                    .collect::<Vec<EntityId>>(),
            )?;
            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("field".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Field>>, Error> {
        let mut list = Vec::new();
        let field_table = self.transaction.open_table(FIELD_TABLE)?;

        let entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE)?;

        if ids.is_empty() {
            let mut iter = field_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                // get entity from junction table

                let fetched_entity: Option<EntityId> = entity_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();

                entity.entity = fetched_entity;

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = field_table.get(id)? {
                    let mut entity = guard.value().clone();

                    // get entity from junction table

                    let fetched_entity: Option<EntityId> = entity_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default()
                        .pop();

                    entity.entity = fetched_entity;

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn update_multi(&mut self, entities: &[Field]) -> Result<Vec<Field>, Error> {
        let mut updated = Vec::new();
        let mut field_table = self.transaction.open_table(FIELD_TABLE)?;

        let mut entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE)?;

        for entity in entities {
            field_table.insert(entity.id, entity)?;

            entity_junction_table.insert(entity.id, {
                entity.entity.clone().into_iter().collect::<Vec<EntityId>>()
            })?;
            updated.push(entity.clone());
        }
        Ok(updated)
    }

    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error> {
        let mut field_table = self.transaction.open_table(FIELD_TABLE)?;

        // forward relationships

        let mut entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE)?;

        // backward relationships

        let mut backward_entity_fields_junction_table = self
            .transaction
            .open_table(FIELD_FROM_ENTITY_FIELDS_JUNCTION_TABLE)?;

        for id in ids {
            field_table.remove(id)?;

            entity_junction_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_entity_fields_junction_table,
                id,
            )?;
        }
        Ok(())
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &FieldRelationshipField,
    ) -> Result<Vec<EntityId>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &FieldRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }

    fn set_relationship_multi(
        &mut self,
        field: &FieldRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), Error> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        for (left_id, entities) in relationships {
            table.insert(left_id, entities)?;
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &FieldRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), Error> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(id.clone(), right_ids.to_vec())?;
        Ok(())
    }
}

pub struct FieldRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> FieldRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        FieldRedbTableRO { transaction }
    }
}

impl<'a> FieldTableRO for FieldRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Field>, Error> {
        let v = self.get_multi(&[id.clone()])?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Field>>, Error> {
        let mut list = Vec::new();
        let field_table = self.transaction.open_table(FIELD_TABLE)?;

        let entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_FIELD_ENTITY_JUNCTION_TABLE)?;

        if ids.is_empty() {
            let mut iter = field_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                // get entity from junction table

                let fetched_entity: Option<EntityId> = entity_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop();

                entity.entity = fetched_entity;

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = field_table.get(id)? {
                    let mut entity = guard.value().clone();

                    // get entity from junction table

                    let fetched_entity: Option<EntityId> = entity_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default()
                        .pop();

                    entity.entity = fetched_entity;

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &FieldRelationshipField,
    ) -> Result<Vec<EntityId>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &FieldRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }
}
