// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use std::fmt::Display;

use crate::{
    database::transactions::Transaction,
    direct_access::repository_factory,
    entities::DtoField,
    event::{DirectAccessEntity, EntityEvent, Event, EventBuffer, Origin},
    snapshot::{EntityTreeSnapshot, TableLevelSnapshot},
    types::EntityId,
};

use crate::direct_access::dto::DtoRelationshipField;
use redb::Error;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DtoFieldRelationshipField {}

impl Display for DtoFieldRelationshipField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub trait DtoFieldTable {
    fn create(&mut self, entity: &DtoField) -> Result<DtoField, Error>;
    fn create_multi(&mut self, entities: &[DtoField]) -> Result<Vec<DtoField>, Error>;
    fn get(&self, id: &EntityId) -> Result<Option<DtoField>, Error>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoField>>, Error>;
    fn update(&mut self, entity: &DtoField) -> Result<DtoField, Error>;
    fn update_multi(&mut self, entities: &[DtoField]) -> Result<Vec<DtoField>, Error>;
    fn delete(&mut self, id: &EntityId) -> Result<(), Error>;
    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error>;
    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, Error>;
    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), Error>;
}

pub trait DtoFieldTableRO {
    fn get(&self, id: &EntityId) -> Result<Option<DtoField>, Error>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoField>>, Error>;
}

pub struct DtoFieldRepository<'a> {
    redb_table: Box<dyn DtoFieldTable + 'a>,
    transaction: &'a Transaction,
}

impl<'a> DtoFieldRepository<'a> {
    pub fn new(redb_table: Box<dyn DtoFieldTable + 'a>, transaction: &'a Transaction) -> Self {
        DtoFieldRepository {
            redb_table,
            transaction,
        }
    }

    pub fn create(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &DtoField,
    ) -> Result<DtoField, Error> {
        let new = self.redb_table.create(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Created)),
            ids: vec![new.id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[DtoField],
    ) -> Result<Vec<DtoField>, Error> {
        let new_entities = self.redb_table.create_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Created)),
            ids: new_entities.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(new_entities)
    }
    pub fn create_with_owner(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &DtoField,
        owner_id: EntityId,
        index: i32,
    ) -> Result<DtoField, Error> {
        let new = self.redb_table.create(entity)?;
        let created_id = new.id;

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        // Insert at index
        if index >= 0 && (index as usize) < relationship_ids.len() {
            relationship_ids.insert(index as usize, created_id);
        } else {
            relationship_ids.push(created_id);
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Created)),
            ids: vec![created_id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_multi_with_owner(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[DtoField],
        owner_id: EntityId,
        index: i32,
    ) -> Result<Vec<DtoField>, Error> {
        let new_entities = self.redb_table.create_multi(entities)?;
        let created_ids: Vec<EntityId> = new_entities.iter().map(|e| e.id).collect();

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        if index >= 0 && (index as usize) < relationship_ids.len() {
            for (i, id) in created_ids.iter().enumerate() {
                relationship_ids.insert(index as usize + i, *id);
            }
        } else {
            relationship_ids.extend(created_ids.iter());
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Created)),
            ids: created_ids,
            data: None,
        });
        Ok(new_entities)
    }

    pub fn get(&self, id: &EntityId) -> Result<Option<DtoField>, Error> {
        self.redb_table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoField>>, Error> {
        self.redb_table.get_multi(ids)
    }

    pub fn update(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &DtoField,
    ) -> Result<DtoField, Error> {
        let updated = self.redb_table.update(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[DtoField],
    ) -> Result<Vec<DtoField>, Error> {
        let updated = self.redb_table.update_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn delete(&mut self, event_buffer: &mut EventBuffer, id: &EntityId) -> Result<(), Error> {
        let entity = match self.redb_table.get(id)? {
            Some(e) => e,
            None => return Ok(()),
        };
        // get all strong forward relationship fields

        // delete all strong relationships, initiating a cascade delete

        // delete entity
        self.redb_table.delete(id)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Removed)),
            ids: vec![*id],
            data: None,
        });
        Ok(())
    }

    pub fn delete_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        ids: &[EntityId],
    ) -> Result<(), Error> {
        let entities = self.redb_table.get_multi(ids)?;
        if entities.is_empty() || entities.iter().all(|e| e.is_none()) {
            return Ok(());
        }

        // get all strong forward relationship fields

        // delete all strong relationships, initiating a cascade delete

        self.redb_table.delete_multi(ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Removed)),
            ids: ids.into(),
            data: None,
        });
        Ok(())
    }
    pub fn get_relationships_from_owner(
        &self,
        owner_id: &EntityId,
    ) -> Result<Vec<EntityId>, Error> {
        let repo = repository_factory::write::create_dto_repository(self.transaction);
        repo.get_relationship(owner_id, &DtoRelationshipField::Fields)
    }

    pub fn set_relationships_in_owner(
        &mut self,
        event_buffer: &mut EventBuffer,
        owner_id: &EntityId,
        ids: &[EntityId],
    ) -> Result<(), Error> {
        let mut repo = repository_factory::write::create_dto_repository(self.transaction);
        repo.set_relationship(event_buffer, owner_id, &DtoRelationshipField::Fields, ids)
    }

    pub fn snapshot(&self, ids: &[EntityId]) -> Result<EntityTreeSnapshot, Error> {
        let table_data = self.redb_table.snapshot_rows(ids)?;

        // Recursively snapshot strong children
        #[allow(unused_mut)]
        let mut children = Vec::new();

        Ok(EntityTreeSnapshot {
            table_data,
            children,
        })
    }

    pub fn restore(
        &mut self,
        event_buffer: &mut EventBuffer,
        snap: &EntityTreeSnapshot,
    ) -> Result<(), Error> {
        // Restore children first (bottom-up)

        // Restore this entity's rows
        self.redb_table.restore_rows(&snap.table_data)?;

        // Emit Created events for restored entity IDs
        let restored_ids: Vec<EntityId> = snap
            .table_data
            .entity_rows
            .rows
            .iter()
            .map(|(id, _)| *id)
            .collect();
        if !restored_ids.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::DtoField(EntityEvent::Created)),
                ids: restored_ids.clone(),
                data: None,
            });
        }
        Ok(())
    }
}

pub struct DtoFieldRepositoryRO<'a> {
    redb_table: Box<dyn DtoFieldTableRO + 'a>,
}
impl<'a> DtoFieldRepositoryRO<'a> {
    pub fn new(redb_table: Box<dyn DtoFieldTableRO + 'a>) -> Self {
        DtoFieldRepositoryRO { redb_table }
    }
    pub fn get(&self, id: &EntityId) -> Result<Option<DtoField>, Error> {
        self.redb_table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoField>>, Error> {
        self.redb_table.get_multi(ids)
    }
}
