// Generated by Qleany v0.0.1 from common_entity_table.tera

use super::dto_field_repository::DtoFieldTable;
use super::dto_field_repository::DtoFieldTableRO;
use crate::database::Bincode;
use crate::database::db_helpers;
use crate::entities::DtoField;
use crate::error::RepositoryError;
use crate::snapshot::{JunctionSnapshot, TableLevelSnapshot, TableSnapshot};
use crate::types::EntityId;
use redb::{ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const DTO_FIELD_TABLE: TableDefinition<EntityId, Bincode<DtoField>> =
    TableDefinition::new("dto_field");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

// backward relationships

const DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("dto_field_from_dto_fields_junction");

pub struct DtoFieldRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> DtoFieldRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        DtoFieldRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), RepositoryError> {
        transaction.open_table(DTO_FIELD_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> DtoFieldTable for DtoFieldRedbTable<'a> {
    fn create(&mut self, entity: &DtoField) -> Result<DtoField, RepositoryError> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<DtoField>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &DtoField) -> Result<DtoField, RepositoryError> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[DtoField]) -> Result<Vec<DtoField>, RepositoryError> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"dto_field".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                DtoField {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if dto_field_table.get(&entity.id)?.is_some() {
                    return Err(RepositoryError::DuplicateId {
                        entity: "DtoField",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            dto_field_table.insert(new_entity.id, new_entity.clone())?;

            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("dto_field".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoField>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = dto_field_table.get(id)? {
                let entity = guard.value().clone();
                let mut _junction_complete = true;

                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<DtoField>, RepositoryError> {
        let mut list = Vec::new();
        let dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        let mut iter = dto_field_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let _id = id.value();
            let entity = data.value().clone();
            let mut _junction_complete = true;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }

    fn update_multi(&mut self, entities: &[DtoField]) -> Result<Vec<DtoField>, RepositoryError> {
        let mut updated = Vec::new();
        let mut dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        for entity in entities {
            dto_field_table.insert(entity.id, entity)?;

            updated.push(entity.clone());
        }
        Ok(updated)
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        // forward relationships

        // backward relationships

        let mut backward_dto_fields_junction_table = self
            .transaction
            .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;

        for id in ids {
            dto_field_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_dto_fields_junction_table,
                id,
            )?;
        }
        Ok(())
    }

    fn snapshot_rows(&self, ids: &[EntityId]) -> Result<TableLevelSnapshot, RepositoryError> {
        let dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        // Snapshot entity rows as bincode bytes
        let mut rows = Vec::new();
        for id in ids {
            if let Some(guard) = dto_field_table.get(id)? {
                let entity = guard.value();
                let bytes = bincode::serialize(&entity)
                    .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
                rows.push((*id, bytes));
            }
        }

        // Snapshot forward junction tables
        let forward_junctions = Vec::new();

        // Snapshot backward junction tables (entries that reference any of the given ids)
        let mut backward_junctions = Vec::new();

        {
            let junction_table = self
                .transaction
                .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;
            let mut entries = Vec::new();
            let mut iter = junction_table.iter()?;
            while let Some(Ok((left_id_guard, right_ids_guard))) = iter.next() {
                let left_id = left_id_guard.value();
                let right_ids = right_ids_guard.value();
                if ids.iter().any(|id| right_ids.contains(id)) {
                    entries.push((left_id, right_ids));
                }
            }
            if !entries.is_empty() {
                backward_junctions.push(JunctionSnapshot {
                    table_name: "dto_field_from_dto_fields_junction".to_string(),
                    entries,
                });
            }
        }

        Ok(TableLevelSnapshot {
            entity_rows: TableSnapshot {
                table_name: "dto_field".to_string(),
                rows,
            },
            forward_junctions,
            backward_junctions,
        })
    }

    fn restore_rows(&mut self, snap: &TableLevelSnapshot) -> Result<(), RepositoryError> {
        let mut dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        // Restore entity rows from bincode bytes (redb insert is upsert)
        for (id, bytes) in &snap.entity_rows.rows {
            let entity: DtoField = bincode::deserialize(bytes)
                .map_err(|e| RepositoryError::Serialization(e.to_string()))?;
            dto_field_table.insert(*id, entity)?;
        }

        // Restore forward junction entries

        // Restore backward junction entries

        {
            let mut junction_table = self
                .transaction
                .open_table(DTO_FIELD_FROM_DTO_FIELDS_JUNCTION_TABLE)?;
            for junction_snap in &snap.backward_junctions {
                if junction_snap.table_name == "dto_field_from_dto_fields_junction" {
                    for (left_id, right_ids) in &junction_snap.entries {
                        junction_table.insert(*left_id, right_ids.clone())?;
                    }
                }
            }
        }

        Ok(())
    }
}

pub struct DtoFieldRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> DtoFieldRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        DtoFieldRedbTableRO { transaction }
    }
}

impl<'a> DtoFieldTableRO for DtoFieldRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<DtoField>, RepositoryError> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DtoField>>, RepositoryError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }
        let mut list = Vec::new();
        let dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        for id in ids {
            let item = if let Some(guard) = dto_field_table.get(id)? {
                let entity = guard.value().clone();
                let mut _junction_complete = true;

                if _junction_complete {
                    Some(entity)
                } else {
                    None
                }
            } else {
                None
            };
            list.push(item);
        }

        Ok(list)
    }

    fn get_all(&self) -> Result<Vec<DtoField>, RepositoryError> {
        let mut list = Vec::new();
        let dto_field_table = self.transaction.open_table(DTO_FIELD_TABLE)?;

        let mut iter = dto_field_table.iter()?;
        while let Some(Ok((id, data))) = iter.next() {
            let _id = id.value();
            let entity = data.value().clone();
            let mut _junction_complete = true;

            if _junction_complete {
                list.push(entity);
            }
        }

        Ok(list)
    }
}
