// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::DtoFieldUnitOfWorkFactoryTrait;
use anyhow::{Ok, Result};
use common::{snapshot::EntityTreeSnapshot, types::EntityId, undo_redo::UndoRedoCommand};
use std::any::Any;

/// Use case to remove a dto_field entity.
/// Supports undo/redo via entity tree snapshots.
pub struct RemoveDtoFieldUseCase {
    uow_factory: Box<dyn DtoFieldUnitOfWorkFactoryTrait>,
    entity_tree_snapshot: Option<EntityTreeSnapshot>,
    original_id: Option<EntityId>,
}

impl RemoveDtoFieldUseCase {
    pub fn new(uow_factory: Box<dyn DtoFieldUnitOfWorkFactoryTrait>) -> Self {
        RemoveDtoFieldUseCase {
            uow_factory,
            entity_tree_snapshot: None,
            original_id: None,
        }
    }

    pub fn execute(&mut self, id: &EntityId) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;
        // check if id exists
        if uow.get_dto_field(id)?.is_none() {
            return Err(anyhow::anyhow!("DtoField with id {} does not exist", id));
        }
        // snapshot the entity tree before deletion (for undo)
        self.entity_tree_snapshot = Some(uow.snapshot_dto_field(&[*id])?);
        uow.delete_dto_field(id)?;
        uow.commit()?;
        self.original_id = Some(*id);

        Ok(())
    }
}
impl UndoRedoCommand for RemoveDtoFieldUseCase {
    fn undo(&mut self) -> Result<()> {
        if let Some(ref snap) = self.entity_tree_snapshot {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            uow.restore_dto_field(snap)?;
            uow.commit()?;
        }
        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        if let Some(id) = self.original_id {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            // re-snapshot before re-deleting (state may have changed)
            self.entity_tree_snapshot = Some(uow.snapshot_dto_field(&[id])?);
            uow.delete_dto_field(&id)?;
            uow.commit()?;
        }
        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
