// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::DtoFieldUnitOfWorkFactoryTrait;
use crate::dto_field::dtos::DtoFieldDto;
use anyhow::{Ok, Result};
use common::{entities::DtoField, undo_redo::UndoRedoCommand};
use std::any::Any;
use std::collections::VecDeque;

pub struct UpdateDtoFieldMultiUseCase {
    uow_factory: Box<dyn DtoFieldUnitOfWorkFactoryTrait>,
    undo_stack: VecDeque<Vec<DtoField>>,
    redo_stack: VecDeque<Vec<DtoField>>,
}

impl UpdateDtoFieldMultiUseCase {
    pub fn new(uow_factory: Box<dyn DtoFieldUnitOfWorkFactoryTrait>) -> Self {
        UpdateDtoFieldMultiUseCase {
            uow_factory,
            undo_stack: VecDeque::new(),
            redo_stack: VecDeque::new(),
        }
    }

    pub fn execute(&mut self, dtos: &[DtoFieldDto]) -> Result<Vec<DtoFieldDto>> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // check if id exists
        let mut exists = true;
        for DtoFieldDto { id, .. } in dtos {
            if uow.get_dto_field(id)?.is_none() {
                exists = false;
                break;
            }
        }
        if !exists {
            return Err(anyhow::anyhow!("One or more ids do not exist"));
        }
        // store in undo stack
        let entities = uow
            .get_dto_field_multi(&dtos.iter().map(|dto| dto.id).collect::<Vec<_>>())?
            .iter()
            .filter_map(|entity| entity.clone())
            .collect();
        self.undo_stack.push_back(entities);

        let entities =
            uow.update_dto_field_multi(&dtos.iter().map(|dto| dto.into()).collect::<Vec<_>>())?;
        uow.commit()?;

        Ok(entities.into_iter().map(|entity| entity.into()).collect())
    }
}

impl UndoRedoCommand for UpdateDtoFieldMultiUseCase {
    fn undo(&mut self) -> Result<()> {
        if let Some(last_entities) = self.undo_stack.pop_back() {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            uow.update_dto_field_multi(&last_entities)?;
            uow.commit()?;
            self.redo_stack.push_back(last_entities);
        }
        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        if let Some(entities) = self.redo_stack.pop_back() {
            let mut uow = self.uow_factory.create();
            uow.begin_transaction()?;
            uow.update_dto_field_multi(&entities)?;
            uow.commit()?;
            self.undo_stack.push_back(entities);
        }
        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
