// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::units_of_work::DtoFieldUnitOfWorkFactory;
use super::{
    dtos::{CreateDtoFieldDto, DtoFieldDto},
    units_of_work::DtoFieldUnitOfWorkROFactory,
    use_cases::{
        create_dto_field_multi_uc::CreateDtoFieldMultiUseCase,
        create_dto_field_uc::CreateDtoFieldUseCase,
        get_dto_field_multi_uc::GetDtoFieldMultiUseCase, get_dto_field_uc::GetDtoFieldUseCase,
        remove_dto_field_multi_uc::RemoveDtoFieldMultiUseCase,
        remove_dto_field_uc::RemoveDtoFieldUseCase,
        update_dto_field_multi_uc::UpdateDtoFieldMultiUseCase,
        update_dto_field_uc::UpdateDtoFieldUseCase,
    },
};
use anyhow::{Ok, Result};

use common::undo_redo::UndoRedoManager;
use common::{database::db_context::DbContext, event::EventHub, types::EntityId};
use std::sync::Arc;

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    entity: &CreateDtoFieldDto,
) -> Result<DtoFieldDto> {
    let uow_factory = DtoFieldUnitOfWorkFactory::new(&db_context, &event_hub);
    let mut uc = CreateDtoFieldUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity.clone())?;
    undo_redo_manager.add_command(Box::new(uc));
    Ok(result)
}

pub fn get(db_context: &DbContext, id: &EntityId) -> Result<Option<DtoFieldDto>> {
    let uow_factory = DtoFieldUnitOfWorkROFactory::new(&db_context);
    let uc = GetDtoFieldUseCase::new(Box::new(uow_factory));
    uc.execute(id)
}

pub fn update(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    entity: &DtoFieldDto,
) -> Result<DtoFieldDto> {
    let uow_factory = DtoFieldUnitOfWorkFactory::new(&db_context, &event_hub);
    let mut uc = UpdateDtoFieldUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entity)?;
    undo_redo_manager.add_command(Box::new(uc));
    Ok(result)
}

pub fn remove(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    id: &EntityId,
) -> Result<()> {
    let uow_factory = DtoFieldUnitOfWorkFactory::new(&db_context, &event_hub);
    let mut uc = RemoveDtoFieldUseCase::new(Box::new(uow_factory));
    uc.execute(id)?;
    undo_redo_manager.add_command(Box::new(uc));
    Ok(())
}

pub fn create_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    entities: &[CreateDtoFieldDto],
) -> Result<Vec<DtoFieldDto>> {
    let uow_factory = DtoFieldUnitOfWorkFactory::new(&db_context, &event_hub);
    let mut uc = CreateDtoFieldMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command(Box::new(uc));
    Ok(result)
}

pub fn get_multi(db_context: &DbContext, ids: &[EntityId]) -> Result<Vec<Option<DtoFieldDto>>> {
    let uow_factory = DtoFieldUnitOfWorkROFactory::new(&db_context);
    let uc = GetDtoFieldMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)
}

pub fn update_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    entities: &[DtoFieldDto],
) -> Result<Vec<DtoFieldDto>> {
    let uow_factory = DtoFieldUnitOfWorkFactory::new(&db_context, &event_hub);
    let mut uc = UpdateDtoFieldMultiUseCase::new(Box::new(uow_factory));
    let result = uc.execute(entities)?;
    undo_redo_manager.add_command(Box::new(uc));
    Ok(result)
}

pub fn remove_multi(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    undo_redo_manager: &mut UndoRedoManager,
    ids: &[EntityId],
) -> Result<()> {
    let uow_factory = DtoFieldUnitOfWorkFactory::new(&db_context, &event_hub);
    let mut uc = RemoveDtoFieldMultiUseCase::new(Box::new(uow_factory));
    uc.execute(ids)?;
    undo_redo_manager.add_command(Box::new(uc));
    Ok(())
}
