// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use common::entities::DtoField;
use common::entities::DtoFieldType;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DtoFieldDto {
    pub id: EntityId,
    pub name: String,
    pub field_type: DtoFieldType,
    pub is_nullable: bool,
    pub is_list: bool,
    pub enum_name: Option<String>,
    pub enum_values: Option<Vec<String>>,
}

impl From<DtoFieldDto> for DtoField {
    fn from(dto: DtoFieldDto) -> Self {
        DtoField {
            id: dto.id,
            name: dto.name,
            field_type: dto.field_type,
            is_nullable: dto.is_nullable,
            is_list: dto.is_list,
            enum_name: dto.enum_name,
            enum_values: dto.enum_values,
        }
    }
}

impl From<&DtoFieldDto> for DtoField {
    fn from(dto: &DtoFieldDto) -> Self {
        DtoField {
            id: dto.id,
            name: dto.name.clone(),
            field_type: dto.field_type.clone(),
            is_nullable: dto.is_nullable.clone(),
            is_list: dto.is_list.clone(),
            enum_name: dto.enum_name.clone(),
            enum_values: dto.enum_values.clone(),
        }
    }
}

impl From<DtoField> for DtoFieldDto {
    fn from(entity: DtoField) -> Self {
        DtoFieldDto {
            id: entity.id,
            name: entity.name,
            field_type: entity.field_type,
            is_nullable: entity.is_nullable,
            is_list: entity.is_list,
            enum_name: entity.enum_name,
            enum_values: entity.enum_values,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDtoFieldDto {
    pub name: String,
    pub field_type: DtoFieldType,
    pub is_nullable: bool,
    pub is_list: bool,
    pub enum_name: Option<String>,
    pub enum_values: Option<Vec<String>>,
}

impl From<CreateDtoFieldDto> for DtoField {
    fn from(dto: CreateDtoFieldDto) -> Self {
        DtoField {
            id: 0,
            name: dto.name,
            field_type: dto.field_type,
            is_nullable: dto.is_nullable,
            is_list: dto.is_list,
            enum_name: dto.enum_name,
            enum_values: dto.enum_values,
        }
    }
}

impl From<&CreateDtoFieldDto> for DtoField {
    fn from(dto: &CreateDtoFieldDto) -> Self {
        DtoField {
            id: 0,
            name: dto.name.clone(),
            field_type: dto.field_type.clone(),
            is_nullable: dto.is_nullable.clone(),
            is_list: dto.is_list.clone(),
            enum_name: dto.enum_name.clone(),
            enum_values: dto.enum_values.clone(),
        }
    }
}

impl From<DtoField> for CreateDtoFieldDto {
    fn from(entity: DtoField) -> Self {
        CreateDtoFieldDto {
            name: entity.name,
            field_type: entity.field_type,
            is_nullable: entity.is_nullable,
            is_list: entity.is_list,
            enum_name: entity.enum_name,
            enum_values: entity.enum_values,
        }
    }
}
