// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{File, System};
use common::types::EntityId;
use anyhow::anyhow;

pub trait FillStatusInFilesUnitOfWorkFactoryTrait {
    fn create(&self) -> Box<dyn FillStatusInFilesUnitOfWorkTrait>;
}
#[macros::uow_action(entity = "Root", action = "GetMulti")]
#[macros::uow_action(entity = "Root", action = "GetRelationship")]
#[macros::uow_action(entity = "System", action = "Get")]
#[macros::uow_action(entity = "System", action = "GetRelationship")]
#[macros::uow_action(entity = "File", action = "GetMulti")]
pub trait FillStatusInFilesUnitOfWorkTrait: CommandUnitOfWork {}

pub struct FillStatusInFilesUseCase {
    uow_factory: Box<dyn FillStatusInFilesUnitOfWorkFactoryTrait>,
}

impl FillStatusInFilesUseCase {
    pub fn new(uow_factory: Box<dyn FillStatusInFilesUnitOfWorkFactoryTrait>) -> Self {
        FillStatusInFilesUseCase { uow_factory }
    }

    pub fn execute(&mut self) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;


        let roots = uow.get_root_multi(&[])?;
        let root = roots
            .into_iter()
            .flatten()
            .next()
            .ok_or_else(|| anyhow!("Root entity not found"))?;

        let all_system_ids = uow.get_root_relationship(
            &root.id,
            &common::direct_access::root::RootRelationshipField::System,
        )?;

        let system_id = all_system_ids
            .first()
            .cloned()
            .ok_or(anyhow!("No system found"))?;
        uow.commit()?;
        Ok(())
    }
}
