// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::CarUnitOfWorkROFactoryTrait;
use crate::car::dtos::CarDto;
use anyhow::Result;
use common::types::EntityId;

pub struct GetCarUseCase {
    uow_factory: Box<dyn CarUnitOfWorkROFactoryTrait>,
}

impl GetCarUseCase {
    pub fn new(uow_factory: Box<dyn CarUnitOfWorkROFactoryTrait>) -> Self {
        GetCarUseCase { uow_factory }
    }

    pub fn execute(&self, id: &EntityId) -> Result<Option<CarDto>> {
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let entity_option = uow.get_car(&id)?;
        uow.end_transaction()?;

        Ok(entity_option.map(|entity| entity.into()))
    }
}
