// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.


//! Dto entity commands for Slint UI

use crate::app_context::AppContext;
use common::direct_access::dto::DtoRelationshipField;
use direct_access::DtoRelationshipDto;
use direct_access::{CreateDtoDto, DtoDto, dto_controller};
use common::types::EntityId;

/// Create a new dto entity (orphan, no parent)
pub fn create_orphans_dto(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateDtoDto,
) -> Result<DtoDto, String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::create_orphans(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dto,
    )
    .map_err(|e| format!("Error creating dto: {:?}", e))
}/// Create a new dto entity as child of owner
pub fn create_dto(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateDtoDto,
    owner_id: EntityId,
    index: i32,
) -> Result<DtoDto, String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .map_err(|e| format!("Error creating dto: {:?}", e))
}/// Create multiple dto entities (orphan, no parent)
pub fn create_orphans_dto_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateDtoDto],
) -> Result<Vec<DtoDto>, String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::create_orphans_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dtos,
    )
    .map_err(|e| format!("Error creating entities: {:?}", e))
}/// Create multiple dto entities as children of owner
pub fn create_dto_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateDtoDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<DtoDto>, String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .map_err(|e| format!("Error creating entities: {:?}", e))
}/// Get a dto entity by ID
pub fn get_dto(ctx: &AppContext, id: &EntityId) -> Result<Option<DtoDto>, String> {
    dto_controller::get(&ctx.db_context, id).map_err(|e| format!("Error getting dto: {:?}", e))
}

/// Get multiple dto entities by IDs
pub fn get_dto_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<Vec<Option<DtoDto>>, String> {
    dto_controller::get_multi(&ctx.db_context, ids)
        .map_err(|e| format!("Error getting entities: {:?}", e))
}

/// Update a dto entity
pub fn update_dto(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &DtoDto,
) -> Result<DtoDto, String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dto,
    )
    .map_err(|e| format!("Error updating dto: {:?}", e))
}

/// Update multiple dto entities
pub fn update_dto_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[DtoDto],
) -> Result<Vec<DtoDto>, String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dtos,
    )
    .map_err(|e| format!("Error updating entities: {:?}", e))
}

/// Remove a dto entity by ID
pub fn remove_dto(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<(), String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    let result = dto_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        id,
    )
    .map_err(|e| format!("Error deleting dto: {:?}", e));

    undo_redo_manager.clear_all_stacks();
    result
    
}

/// Remove multiple dto entities by IDs
pub fn remove_dto_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<(), String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    let result = dto_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        ids,
    )
    .map_err(|e| format!("Error deleting dto: {:?}", e));

    undo_redo_manager.clear_all_stacks();
    result
    
}

/// Get a dto relationship
pub fn get_dto_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &DtoRelationshipField,
) -> Result<Vec<EntityId>, String> {
    dto_controller::get_relationship(&ctx.db_context, id, field)
        .map_err(|e| format!("Error getting dto relationship: {:?}", e))
}

/// Set a dto relationship
pub fn set_dto_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &DtoRelationshipDto,
) -> Result<(), String> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    dto_controller::set_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut *undo_redo_manager,
        stack_id,
        dto,
    )
    
    .map_err(|e| format!("Error setting dto relationship: {:?}", e))
}




