// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.


//! HandlingManifest feature commands for Slint UI

use crate::app_context::AppContext;
use handling_manifest::{
    ExportToMermaidReturnDto,
    LoadDto,
    LoadReturnDto,
    NewReturnDto,
    SaveDto,
    handling_manifest_controller,
};



pub fn load(
    ctx: &AppContext,
    dto: &LoadDto,
) -> Result<LoadReturnDto, String> {
    handling_manifest_controller::load(
        &ctx.db_context,
        &ctx.event_hub,
        dto,
    )
    .map_err(|e| format!("Error while load: {:?}", e))
}

pub fn save(
    ctx: &AppContext,
    dto: &SaveDto,
) -> Result<(), String> {
    handling_manifest_controller::save(
        &ctx.db_context,
        &ctx.event_hub,
        dto,
    )
    .map_err(|e| format!("Error while save: {:?}", e))
}

pub fn create(
    ctx: &AppContext,
) -> Result<NewReturnDto, String> {
    handling_manifest_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
    )
    .map_err(|e| format!("Error while create: {:?}", e))
}

pub fn close(
    ctx: &AppContext,
) -> Result<(), String> {
    handling_manifest_controller::close(
        &ctx.db_context,
        &ctx.event_hub,
    )
    .map_err(|e| format!("Error while close: {:?}", e))
}

pub fn export_to_mermaid(
    ctx: &AppContext,
) -> Result<ExportToMermaidReturnDto, String> {
    handling_manifest_controller::export_to_mermaid(
        &ctx.db_context,
        &ctx.event_hub,
    )
    .map_err(|e| format!("Error while export_to_mermaid: {:?}", e))
}
