// Generated by Qleany v1.7.0 from common_entity_table.tera

// ═══════════════════════════════════════════════════════════════════════
// Leaf entity (no forward relationships) — macro implementation
// ═══════════════════════════════════════════════════════════════════════

use super::user_interface_repository::UserInterfaceTable;
use super::user_interface_repository::UserInterfaceTableRO;
use crate::entities::UserInterface;
use crate::error::RepositoryError;
use crate::types::EntityId;

crate::impl_leaf_entity_table!(
    entity: UserInterface,
    entity_name: "user_interface",
    store_field: user_interfaces,
    table_trait: UserInterfaceTable,
    table_ro_trait: UserInterfaceTableRO,
    table_struct: UserInterfaceHashMapTable,
    table_ro_struct: UserInterfaceHashMapTableRO,
    backward_junctions: [

        (jn_user_interface_from_workspace_user_interface),
    ],
);
