// Generated by Qleany v1.7.0 from common_entity_repository.tera

use std::fmt::Display;

use crate::{
    database::transactions::Transaction,
    direct_access::repository_factory,
    entities::UserInterface,
    event::{DirectAccessEntity, EntityEvent, Event, EventBuffer, Origin},
    snapshot::EntityTreeSnapshot,
    types::EntityId,
};

use crate::direct_access::workspace::WorkspaceRelationshipField;
use crate::error::RepositoryError;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum UserInterfaceRelationshipField {}

impl Display for UserInterfaceRelationshipField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub trait UserInterfaceTable {
    fn create(&mut self, entity: &UserInterface) -> Result<UserInterface, RepositoryError>;
    fn create_multi(
        &mut self,
        entities: &[UserInterface],
    ) -> Result<Vec<UserInterface>, RepositoryError>;
    fn get(&self, id: &EntityId) -> Result<Option<UserInterface>, RepositoryError>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<UserInterface>>, RepositoryError>;
    fn get_all(&self) -> Result<Vec<UserInterface>, RepositoryError>;
    fn update(&mut self, entity: &UserInterface) -> Result<UserInterface, RepositoryError>;
    fn update_multi(
        &mut self,
        entities: &[UserInterface],
    ) -> Result<Vec<UserInterface>, RepositoryError>;
    fn update_with_relationships(
        &mut self,
        entity: &UserInterface,
    ) -> Result<UserInterface, RepositoryError>;
    fn update_with_relationships_multi(
        &mut self,
        entities: &[UserInterface],
    ) -> Result<Vec<UserInterface>, RepositoryError>;
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError>;
    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError>;
}

pub trait UserInterfaceTableRO {
    fn get(&self, id: &EntityId) -> Result<Option<UserInterface>, RepositoryError>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<UserInterface>>, RepositoryError>;
    fn get_all(&self) -> Result<Vec<UserInterface>, RepositoryError>;
}

pub struct UserInterfaceRepository<'a> {
    table: Box<dyn UserInterfaceTable + 'a>,
    transaction: &'a Transaction,
}

impl<'a> UserInterfaceRepository<'a> {
    pub fn new(table: Box<dyn UserInterfaceTable + 'a>, transaction: &'a Transaction) -> Self {
        UserInterfaceRepository { table, transaction }
    }

    pub fn create_orphan(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &UserInterface,
    ) -> Result<UserInterface, RepositoryError> {
        let new = self.table.create(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Created)),
            ids: vec![new.id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_orphan_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[UserInterface],
    ) -> Result<Vec<UserInterface>, RepositoryError> {
        let new_entities = self.table.create_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Created)),
            ids: new_entities.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(new_entities)
    }
    pub fn create(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &UserInterface,
        owner_id: EntityId,
        _index: i32,
    ) -> Result<UserInterface, RepositoryError> {
        let new = self.table.create(entity)?;
        let created_id = new.id;

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        if relationship_ids.is_empty() {
            relationship_ids = vec![created_id];
        } else {
            // Replace existing relationship: cascade-remove old entities first
            self.remove_multi(event_buffer, &relationship_ids)?;
            relationship_ids = vec![created_id];
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Created)),
            ids: vec![created_id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[UserInterface],
        owner_id: EntityId,
        _index: i32,
    ) -> Result<Vec<UserInterface>, RepositoryError> {
        let new_entities = self.table.create_multi(entities)?;
        let created_ids: Vec<EntityId> = new_entities.iter().map(|e| e.id).collect();

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        if relationship_ids.is_empty() {
            relationship_ids = created_ids.clone();
        } else {
            self.remove_multi(event_buffer, &relationship_ids)?;
            relationship_ids = created_ids.clone();
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Created)),
            ids: created_ids,
            data: None,
        });
        Ok(new_entities)
    }

    pub fn get(&self, id: &EntityId) -> Result<Option<UserInterface>, RepositoryError> {
        self.table.get(id)
    }
    pub fn get_multi(
        &self,
        ids: &[EntityId],
    ) -> Result<Vec<Option<UserInterface>>, RepositoryError> {
        self.table.get_multi(ids)
    }
    pub fn get_all(&self) -> Result<Vec<UserInterface>, RepositoryError> {
        self.table.get_all()
    }

    pub fn update(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &UserInterface,
    ) -> Result<UserInterface, RepositoryError> {
        let updated = self.table.update(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[UserInterface],
    ) -> Result<Vec<UserInterface>, RepositoryError> {
        let updated = self.table.update_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn update_with_relationships(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &UserInterface,
    ) -> Result<UserInterface, RepositoryError> {
        let updated = self.table.update_with_relationships(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_with_relationships_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[UserInterface],
    ) -> Result<Vec<UserInterface>, RepositoryError> {
        let updated = self.table.update_with_relationships_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn remove(
        &mut self,
        event_buffer: &mut EventBuffer,
        id: &EntityId,
    ) -> Result<(), RepositoryError> {
        let _entity = match self.table.get(id)? {
            Some(e) => e,
            None => return Ok(()),
        };
        // get all strong forward relationship fields

        // remove all strong relationships, initiating a cascade remove

        // Before removal, find which owner(s) reference this entity
        let affected_owner_ids: Vec<EntityId> = {
            let owner_repo =
                repository_factory::write::create_workspace_repository(self.transaction)?;
            owner_repo
                .get_relationships_from_right_ids(
                    &WorkspaceRelationshipField::UserInterface,
                    &[*id],
                )?
                .into_iter()
                .map(|(owner_id, _)| owner_id)
                .collect()
        };
        // Save each owner's current relationship IDs (properly ordered via get_relationships_from_owner)
        let mut owner_rel_before: std::collections::HashMap<EntityId, Vec<EntityId>> =
            std::collections::HashMap::new();
        for owner_id in &affected_owner_ids {
            owner_rel_before.insert(*owner_id, self.get_relationships_from_owner(owner_id)?);
        }

        // remove entity
        self.table.remove(id)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Removed)),
            ids: vec![*id],
            data: None,
        });
        // Update each affected owner's relationship to exclude removed ID (emits Updated event)
        for owner_id in &affected_owner_ids {
            if let Some(rel_ids) = owner_rel_before.get(owner_id) {
                let updated: Vec<EntityId> =
                    rel_ids.iter().copied().filter(|rid| *rid != *id).collect();
                self.set_relationships_in_owner(event_buffer, owner_id, &updated)?;
            }
        }

        Ok(())
    }

    pub fn remove_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let entities = self.table.get_multi(ids)?;
        if entities.is_empty() || entities.iter().all(|e| e.is_none()) {
            return Ok(());
        }

        // get all strong forward relationship fields

        // remove all strong relationships, initiating a cascade remove

        // Before removal, find which owner(s) reference these entities
        let affected_owner_ids: Vec<EntityId> = {
            let owner_repo =
                repository_factory::write::create_workspace_repository(self.transaction)?;
            owner_repo
                .get_relationships_from_right_ids(&WorkspaceRelationshipField::UserInterface, ids)?
                .into_iter()
                .map(|(owner_id, _)| owner_id)
                .collect()
        };
        // Save each owner's current relationship IDs (properly ordered via get_relationships_from_owner)
        let mut owner_rel_before: std::collections::HashMap<EntityId, Vec<EntityId>> =
            std::collections::HashMap::new();
        for owner_id in &affected_owner_ids {
            owner_rel_before.insert(*owner_id, self.get_relationships_from_owner(owner_id)?);
        }

        self.table.remove_multi(ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Removed)),
            ids: ids.into(),
            data: None,
        });
        // Update each affected owner's relationship to exclude removed IDs (emits Updated event)
        {
            let removed_set: std::collections::HashSet<EntityId> = ids.iter().copied().collect();
            for owner_id in &affected_owner_ids {
                if let Some(rel_ids) = owner_rel_before.get(owner_id) {
                    let updated: Vec<EntityId> = rel_ids
                        .iter()
                        .copied()
                        .filter(|rid| !removed_set.contains(rid))
                        .collect();
                    self.set_relationships_in_owner(event_buffer, owner_id, &updated)?;
                }
            }
        }

        Ok(())
    }
    pub fn get_relationships_from_owner(
        &self,
        owner_id: &EntityId,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let repo = repository_factory::write::create_workspace_repository(self.transaction)?;
        repo.get_relationship(owner_id, &WorkspaceRelationshipField::UserInterface)
    }

    pub fn set_relationships_in_owner(
        &mut self,
        event_buffer: &mut EventBuffer,
        owner_id: &EntityId,
        ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut repo = repository_factory::write::create_workspace_repository(self.transaction)?;
        repo.set_relationship(
            event_buffer,
            owner_id,
            &WorkspaceRelationshipField::UserInterface,
            ids,
        )
    }

    pub fn snapshot(&self, _ids: &[EntityId]) -> Result<EntityTreeSnapshot, RepositoryError> {
        let store_snap = self.transaction.snapshot_store();
        Ok(EntityTreeSnapshot {
            store_snapshot: Some(store_snap),
        })
    }

    pub fn restore(
        &mut self,
        event_buffer: &mut EventBuffer,
        snap: &EntityTreeSnapshot,
    ) -> Result<(), RepositoryError> {
        let store_snap = snap
            .store_snapshot
            .as_ref()
            .ok_or_else(|| RepositoryError::Serialization("missing store snapshot".into()))?;
        self.transaction.restore_store(store_snap);

        let store = self.transaction.get_store();

        let mut emit = |entity: DirectAccessEntity, ids: Vec<EntityId>| {
            if !ids.is_empty() {
                event_buffer.push(Event {
                    origin: Origin::DirectAccess(entity),
                    ids,
                    data: None,
                });
            }
        };

        // Emit Created events for this entity
        let user_interface_ids: Vec<_> = store
            .user_interfaces
            .read()
            .unwrap()
            .keys()
            .copied()
            .collect();
        emit(
            DirectAccessEntity::UserInterface(EntityEvent::Created),
            user_interface_ids.clone(),
        );

        // Emit Created events for strong children

        Ok(())
    }
}

pub struct UserInterfaceRepositoryRO<'a> {
    table: Box<dyn UserInterfaceTableRO + 'a>,
}
impl<'a> UserInterfaceRepositoryRO<'a> {
    pub fn new(table: Box<dyn UserInterfaceTableRO + 'a>) -> Self {
        UserInterfaceRepositoryRO { table }
    }
    pub fn get(&self, id: &EntityId) -> Result<Option<UserInterface>, RepositoryError> {
        self.table.get(id)
    }
    pub fn get_multi(
        &self,
        ids: &[EntityId],
    ) -> Result<Vec<Option<UserInterface>>, RepositoryError> {
        self.table.get_multi(ids)
    }
    pub fn get_all(&self) -> Result<Vec<UserInterface>, RepositoryError> {
        self.table.get_all()
    }
}
