// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::relationship_repository::RelationshipRelationshipField;
use super::relationship_repository::RelationshipTable;
use super::relationship_repository::RelationshipTableRO;
use crate::database::Bincode;
use crate::database::db_helpers;
use crate::entities::Relationship;
use crate::types::EntityId;
use redb::{Error, ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const RELATIONSHIP_TABLE: TableDefinition<EntityId, Bincode<Relationship>> =
    TableDefinition::new("relationship");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

const ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("entity_from_relationship_left_entity_junction");
const ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("entity_from_relationship_right_entity_junction");
// backward relationships

const RELATIONSHIP_FROM_ENTITY_RELATIONSHIPS_JUNCTION_TABLE: TableDefinition<
    EntityId,
    Vec<EntityId>,
> = TableDefinition::new("relationship_from_entity_relationships_junction");

fn get_junction_table_definition(
    field: &'_ RelationshipRelationshipField,
) -> TableDefinition<'_, EntityId, Vec<EntityId>> {
    match field {
        RelationshipRelationshipField::LeftEntity => {
            ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE
        }
        RelationshipRelationshipField::RightEntity => {
            ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE
        }
    }
}

pub struct RelationshipRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> RelationshipRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        RelationshipRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), Error> {
        transaction.open_table(RELATIONSHIP_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE)?;
        transaction.open_table(ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE)?;

        transaction.open_table(RELATIONSHIP_FROM_ENTITY_RELATIONSHIPS_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> RelationshipTable for RelationshipRedbTable<'a> {
    fn create(&mut self, entity: &Relationship) -> Result<Relationship, Error> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<Relationship>, Error> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &Relationship) -> Result<Relationship, Error> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn delete(&mut self, id: &EntityId) -> Result<(), Error> {
        self.delete_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[Relationship]) -> Result<Vec<Relationship>, Error> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"relationship".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut relationship_table = self.transaction.open_table(RELATIONSHIP_TABLE)?;

        let mut left_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE)?;
        let mut right_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                Relationship {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if relationship_table.get(&entity.id)?.is_some() {
                    return Err(Error::TableDoesNotExist(
                        format!("UseCase id {} already in use", &entity.id).to_string(),
                    ));
                }
                entity.clone()
            };

            relationship_table.insert(new_entity.id, new_entity.clone())?;

            left_entity_junction_table
                .insert(new_entity.id, vec![new_entity.left_entity] as Vec<EntityId>)?;
            right_entity_junction_table.insert(
                new_entity.id,
                vec![new_entity.right_entity] as Vec<EntityId>,
            )?;
            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("relationship".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Relationship>>, Error> {
        let mut list = Vec::new();
        let relationship_table = self.transaction.open_table(RELATIONSHIP_TABLE)?;

        let left_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE)?;
        let right_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE)?;

        if ids.is_empty() {
            let mut iter = relationship_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                // get left_entity from junction table

                let fetched_left_entity: EntityId = left_entity_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop()
                    .expect("Relationship has no left_entity");

                entity.left_entity = fetched_left_entity;

                // get right_entity from junction table

                let fetched_right_entity: EntityId = right_entity_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop()
                    .expect("Relationship has no right_entity");

                entity.right_entity = fetched_right_entity;

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = relationship_table.get(id)? {
                    let mut entity = guard.value().clone();

                    // get left_entity from junction table

                    let fetched_left_entity: EntityId = left_entity_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default()
                        .pop()
                        .expect("Relationship has no left_entity");

                    entity.left_entity = fetched_left_entity;

                    // get right_entity from junction table

                    let fetched_right_entity: EntityId = right_entity_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default()
                        .pop()
                        .expect("Relationship has no right_entity");

                    entity.right_entity = fetched_right_entity;

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn update_multi(&mut self, entities: &[Relationship]) -> Result<Vec<Relationship>, Error> {
        let mut updated = Vec::new();
        let mut relationship_table = self.transaction.open_table(RELATIONSHIP_TABLE)?;

        let mut left_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE)?;
        let mut right_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE)?;

        for entity in entities {
            relationship_table.insert(entity.id, entity)?;

            left_entity_junction_table
                .insert(entity.id, vec![entity.left_entity] as Vec<EntityId>)?;

            right_entity_junction_table
                .insert(entity.id, vec![entity.right_entity] as Vec<EntityId>)?;

            updated.push(entity.clone());
        }
        Ok(updated)
    }

    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error> {
        let mut relationship_table = self.transaction.open_table(RELATIONSHIP_TABLE)?;

        // forward relationships

        let mut left_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE)?;

        let mut right_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE)?;

        // backward relationships

        let mut backward_entity_relationships_junction_table = self
            .transaction
            .open_table(RELATIONSHIP_FROM_ENTITY_RELATIONSHIPS_JUNCTION_TABLE)?;

        for id in ids {
            relationship_table.remove(id)?;

            left_entity_junction_table.remove(id)?;
            right_entity_junction_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_entity_relationships_junction_table,
                id,
            )?;
        }
        Ok(())
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &RelationshipRelationshipField,
    ) -> Result<Vec<EntityId>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &RelationshipRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }

    fn set_relationship_multi(
        &mut self,
        field: &RelationshipRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), Error> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        for (left_id, entities) in relationships {
            table.insert(left_id, entities)?;
        }
        Ok(())
    }

    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &RelationshipRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), Error> {
        let mut table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        table.insert(*id, right_ids.to_vec())?;
        Ok(())
    }
}

pub struct RelationshipRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> RelationshipRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        RelationshipRedbTableRO { transaction }
    }
}

impl<'a> RelationshipTableRO for RelationshipRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Relationship>, Error> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Relationship>>, Error> {
        let mut list = Vec::new();
        let relationship_table = self.transaction.open_table(RELATIONSHIP_TABLE)?;

        let left_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_LEFT_ENTITY_JUNCTION_TABLE)?;
        let right_entity_junction_table = self
            .transaction
            .open_table(ENTITY_FROM_RELATIONSHIP_RIGHT_ENTITY_JUNCTION_TABLE)?;

        if ids.is_empty() {
            let mut iter = relationship_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                // get left_entity from junction table

                let fetched_left_entity: EntityId = left_entity_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop()
                    .expect("Relationship has no left_entity");

                entity.left_entity = fetched_left_entity;

                // get right_entity from junction table

                let fetched_right_entity: EntityId = right_entity_junction_table
                    .get(&id)?
                    .map(|g| g.value().clone())
                    .unwrap_or_default()
                    .pop()
                    .expect("Relationship has no right_entity");

                entity.right_entity = fetched_right_entity;

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = relationship_table.get(id)? {
                    let mut entity = guard.value().clone();

                    // get left_entity from junction table

                    let fetched_left_entity: EntityId = left_entity_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default()
                        .pop()
                        .expect("Relationship has no left_entity");

                    entity.left_entity = fetched_left_entity;

                    // get right_entity from junction table

                    let fetched_right_entity: EntityId = right_entity_junction_table
                        .get(id)?
                        .map(|g| g.value().clone())
                        .unwrap_or_default()
                        .pop()
                        .expect("Relationship has no right_entity");

                    entity.right_entity = fetched_right_entity;

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn get_relationship(
        &self,
        id: &EntityId,
        field: &RelationshipRelationshipField,
    ) -> Result<Vec<EntityId>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let guard = table.get(id)?;
        Ok(guard.map(|g| g.value().clone()).unwrap_or_default())
    }

    fn get_relationships_from_right_ids(
        &self,
        field: &RelationshipRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, Error> {
        let table = self
            .transaction
            .open_table(get_junction_table_definition(field))?;
        let mut iter = table.iter()?;
        let mut rels = vec![];
        while let Some(Ok((left_id, right_entities))) = iter.next() {
            let left_id = left_id.value();
            let right_entities = right_entities.value();
            if right_ids.iter().any(|eid| right_entities.contains(eid)) {
                rels.push((left_id, right_entities));
            }
        }
        Ok(rels)
    }
}
