// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use common::entities::Customer;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomerDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub email: String,
    pub phone: Option<String>,
}

impl From<CustomerDto> for Customer {
    fn from(dto: CustomerDto) -> Self {
        Customer {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            email: dto.email,
            phone: dto.phone,
        }
    }
}

impl From<&CustomerDto> for Customer {
    fn from(dto: &CustomerDto) -> Self {
        Customer {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            email: dto.email.clone(),
            phone: dto.phone.clone(),
        }
    }
}

impl From<Customer> for CustomerDto {
    fn from(entity: Customer) -> Self {
        CustomerDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            email: entity.email,
            phone: entity.phone,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCustomerDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub email: String,
    pub phone: Option<String>,
}

impl From<CreateCustomerDto> for Customer {
    fn from(dto: CreateCustomerDto) -> Self {
        Customer {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            email: dto.email,
            phone: dto.phone,
        }
    }
}

impl From<&CreateCustomerDto> for Customer {
    fn from(dto: &CreateCustomerDto) -> Self {
        Customer {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            email: dto.email.clone(),
            phone: dto.phone.clone(),
        }
    }
}

impl From<Customer> for CreateCustomerDto {
    fn from(entity: Customer) -> Self {
        CreateCustomerDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            email: entity.email,
            phone: entity.phone,
        }
    }
}
