#pragma once

#include <QtCore/QtGlobal>

#if defined(SIMPLEEXAMPLE_PRESENTER_LIBRARY)
#define SIMPLEEXAMPLE_PRESENTER_EXPORT Q_DECL_EXPORT
#else // if defined(SIMPLEEXAMPLE_PRESENTER_LIBRARY)
#define SIMPLEEXAMPLE_PRESENTER_EXPORT Q_DECL_IMPORT
#endif // if defined(SIMPLEEXAMPLE_PRESENTER_LIBRARY)