// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::use_cases::{
    SystemUnitOfWorkFactoryTrait, SystemUnitOfWorkROFactoryTrait, SystemUnitOfWorkROTrait,
    SystemUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::{CommandUnitOfWork, QueryUnitOfWork};
use common::database::{db_context::DbContext, transactions::Transaction};
use common::entities::System;
use common::event::{AllEvent, DirectAccessEntity, Event, EventHub, Origin};
use common::types;
use common::types::EntityId;
use std::cell::RefCell;
use std::sync::Arc;

pub struct SystemUnitOfWork {
    context: DbContext,
    transaction: Option<Transaction>,
    event_hub: Arc<EventHub>,
}

impl SystemUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        SystemUnitOfWork {
            context: db_context.clone(),
            transaction: None,
            event_hub: event_hub.clone(),
        }
    }
}

impl CommandUnitOfWork for SystemUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        self.transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        self.transaction.take().unwrap().commit()?;
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        self.transaction.take().unwrap().rollback()?;
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        self.transaction.as_ref().unwrap().create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction = self.transaction.take().unwrap();
        transaction.restore_to_savepoint(savepoint)?;

        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        // Recreate the transaction after restoring to savepoint
        self.transaction = Some(transaction);

        Ok(())
    }
}

#[macros::uow_action(entity = "System", action = "Create")]
#[macros::uow_action(entity = "System", action = "CreateMulti")]
#[macros::uow_action(entity = "System", action = "Get")]
#[macros::uow_action(entity = "System", action = "GetMulti")]
#[macros::uow_action(entity = "System", action = "Update")]
#[macros::uow_action(entity = "System", action = "UpdateMulti")]
#[macros::uow_action(entity = "System", action = "Delete")]
#[macros::uow_action(entity = "System", action = "DeleteMulti")]
#[macros::uow_action(entity = "System", action = "GetRelationship")]
#[macros::uow_action(entity = "System", action = "GetRelationshipsFromRightIds")]
#[macros::uow_action(entity = "System", action = "SetRelationship")]
#[macros::uow_action(entity = "System", action = "SetRelationshipMulti")]
impl SystemUnitOfWorkTrait for SystemUnitOfWork {}

pub struct SystemUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl SystemUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        SystemUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl SystemUnitOfWorkFactoryTrait for SystemUnitOfWorkFactory {
    fn create(&self) -> Box<dyn SystemUnitOfWorkTrait> {
        Box::new(SystemUnitOfWork::new(&self.context, &self.event_hub))
    }
}

pub struct SystemUnitOfWorkRO {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
}

impl SystemUnitOfWorkRO {
    pub fn new(db_context: &DbContext) -> Self {
        SystemUnitOfWorkRO {
            context: db_context.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for SystemUnitOfWorkRO {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction.take().unwrap().end_read_transaction()?;
        Ok(())
    }
}

#[macros::uow_action(entity = "System", action = "GetRO")]
#[macros::uow_action(entity = "System", action = "GetMultiRO")]
#[macros::uow_action(entity = "System", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "System", action = "GetRelationshipsFromRightIdsRO")]
impl SystemUnitOfWorkROTrait for SystemUnitOfWorkRO {}

pub struct SystemUnitOfWorkROFactory {
    context: DbContext,
}

impl SystemUnitOfWorkROFactory {
    pub fn new(db_context: &DbContext) -> Self {
        SystemUnitOfWorkROFactory {
            context: db_context.clone(),
        }
    }
}

impl SystemUnitOfWorkROFactoryTrait for SystemUnitOfWorkROFactory {
    fn create(&self) -> Box<dyn SystemUnitOfWorkROTrait> {
        Box::new(SystemUnitOfWorkRO::new(&self.context))
    }
}
