// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use super::file_repository::FileRelationshipField;
use super::file_repository::FileTable;
use super::file_repository::FileTableRO;
use crate::database::Bincode;
use crate::database::db_helpers;
use crate::entities::File;
use crate::types::EntityId;
use redb::{Error, ReadTransaction, ReadableTable, TableDefinition, WriteTransaction};

const FILE_TABLE: TableDefinition<EntityId, Bincode<File>> = TableDefinition::new("file");
const COUNTER_TABLE: TableDefinition<String, EntityId> = TableDefinition::new("__counter");
// forward relationships

// backward relationships

const FILE_FROM_SYSTEM_FILES_JUNCTION_TABLE: TableDefinition<EntityId, Vec<EntityId>> =
    TableDefinition::new("file_from_system_files_junction");

pub struct FileRedbTable<'a> {
    transaction: &'a WriteTransaction,
}
impl<'a> FileRedbTable<'a> {
    pub fn new(transaction: &'a WriteTransaction) -> Self {
        FileRedbTable { transaction }
    }

    pub fn init_tables(transaction: &WriteTransaction) -> Result<(), Error> {
        transaction.open_table(FILE_TABLE)?;
        transaction.open_table(COUNTER_TABLE)?;

        transaction.open_table(FILE_FROM_SYSTEM_FILES_JUNCTION_TABLE)?;
        Ok(())
    }
}

impl<'a> FileTable for FileRedbTable<'a> {
    fn create(&mut self, entity: &File) -> Result<File, Error> {
        let v = self.create_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn get(&self, id: &EntityId) -> Result<Option<File>, Error> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn update(&mut self, entity: &File) -> Result<File, Error> {
        let v = self.update_multi(std::slice::from_ref(entity))?;
        Ok(v.into_iter().next().unwrap())
    }
    fn delete(&mut self, id: &EntityId) -> Result<(), Error> {
        self.delete_multi(std::slice::from_ref(id))
    }

    fn create_multi(&mut self, entities: &[File]) -> Result<Vec<File>, Error> {
        let mut created = Vec::new();
        let mut counter_table = self.transaction.open_table(COUNTER_TABLE)?;
        let mut counter = if let Some(counter) = counter_table.get(&"file".to_string())? {
            counter.value()
        } else {
            1
        };
        let mut file_table = self.transaction.open_table(FILE_TABLE)?;

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                File {
                    id: counter,
                    ..entity.clone()
                }
            } else {
                if file_table.get(&entity.id)?.is_some() {
                    return Err(Error::TableDoesNotExist(
                        format!("UseCase id {} already in use", &entity.id).to_string(),
                    ));
                }
                entity.clone()
            };

            file_table.insert(new_entity.id, new_entity.clone())?;

            created.push(new_entity);
            if entity.id == EntityId::default() {
                counter += 1;
            }
        }
        counter_table.insert("file".to_string(), counter)?;
        Ok(created)
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<File>>, Error> {
        let mut list = Vec::new();
        let file_table = self.transaction.open_table(FILE_TABLE)?;

        if ids.is_empty() {
            let mut iter = file_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = file_table.get(id)? {
                    let mut entity = guard.value().clone();

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }

    fn update_multi(&mut self, entities: &[File]) -> Result<Vec<File>, Error> {
        let mut updated = Vec::new();
        let mut file_table = self.transaction.open_table(FILE_TABLE)?;

        for entity in entities {
            file_table.insert(entity.id, entity)?;

            updated.push(entity.clone());
        }
        Ok(updated)
    }

    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error> {
        let mut file_table = self.transaction.open_table(FILE_TABLE)?;

        // forward relationships

        // backward relationships

        let mut backward_system_files_junction_table = self
            .transaction
            .open_table(FILE_FROM_SYSTEM_FILES_JUNCTION_TABLE)?;

        for id in ids {
            file_table.remove(id)?;

            db_helpers::delete_from_backward_junction_table(
                &mut backward_system_files_junction_table,
                id,
            )?;
        }
        Ok(())
    }
}

pub struct FileRedbTableRO<'a> {
    transaction: &'a ReadTransaction,
}
impl<'a> FileRedbTableRO<'a> {
    pub fn new(transaction: &'a ReadTransaction) -> Self {
        FileRedbTableRO { transaction }
    }
}

impl<'a> FileTableRO for FileRedbTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<File>, Error> {
        let v = self.get_multi(std::slice::from_ref(id))?;
        Ok(v.into_iter().next().unwrap())
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<File>>, Error> {
        let mut list = Vec::new();
        let file_table = self.transaction.open_table(FILE_TABLE)?;

        if ids.is_empty() {
            let mut iter = file_table.iter()?;
            let mut count = 0;

            while let Some(Ok((id, data))) = iter.next() {
                if count >= 1000 {
                    break;
                }

                let id = id.value();
                let mut entity = data.value().clone();

                list.push(Some(entity));
                count += 1;
            }
        } else {
            for id in ids {
                let item = if let Some(guard) = file_table.get(id)? {
                    let mut entity = guard.value().clone();

                    Some(entity)
                } else {
                    None
                };
                list.push(item);
            }
        }

        Ok(list)
    }
}
