// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use std::fmt::Display;
use std::sync::Arc;

use crate::{
    database::transactions::Transaction,
    direct_access::repository_factory,
    entities::Customer,
    event::{DirectAccessEntity, EntityEvent, Event, EventHub, Origin},
    types::EntityId,
};

use redb::Error;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CustomerRelationshipField {}

impl Display for CustomerRelationshipField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub trait CustomerTable {
    fn create(&mut self, entity: &Customer) -> Result<Customer, Error>;
    fn create_multi(&mut self, entities: &[Customer]) -> Result<Vec<Customer>, Error>;
    fn get(&self, id: &EntityId) -> Result<Option<Customer>, Error>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Customer>>, Error>;
    fn update(&mut self, entity: &Customer) -> Result<Customer, Error>;
    fn update_multi(&mut self, entities: &[Customer]) -> Result<Vec<Customer>, Error>;
    fn delete(&mut self, id: &EntityId) -> Result<(), Error>;
    fn delete_multi(&mut self, ids: &[EntityId]) -> Result<(), Error>;
}

pub trait CustomerTableRO {
    fn get(&self, id: &EntityId) -> Result<Option<Customer>, Error>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Customer>>, Error>;
}

pub struct CustomerRepository<'a> {
    redb_table: Box<dyn CustomerTable + 'a>,
    transaction: &'a Transaction,
}

impl<'a> CustomerRepository<'a> {
    pub fn new(redb_table: Box<dyn CustomerTable + 'a>, transaction: &'a Transaction) -> Self {
        CustomerRepository {
            redb_table,
            transaction,
        }
    }

    pub fn create(
        &mut self,
        event_hub: &Arc<EventHub>,
        entity: &Customer,
    ) -> Result<Customer, Error> {
        let new = self.redb_table.create(entity)?;
        event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Customer(EntityEvent::Created)),
            ids: vec![new.id.clone()],
            data: None,
        });
        Ok(new)
    }

    pub fn create_multi(
        &mut self,
        event_hub: &Arc<EventHub>,
        entities: &[Customer],
    ) -> Result<Vec<Customer>, Error> {
        let new_entities = self.redb_table.create_multi(entities)?;
        event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Customer(EntityEvent::Created)),
            ids: new_entities.iter().map(|e| e.id.clone()).collect(),
            data: None,
        });
        Ok(new_entities)
    }

    pub fn get(&self, id: &EntityId) -> Result<Option<Customer>, Error> {
        self.redb_table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Customer>>, Error> {
        self.redb_table.get_multi(ids)
    }

    pub fn update(
        &mut self,
        event_hub: &Arc<EventHub>,
        entity: &Customer,
    ) -> Result<Customer, Error> {
        let updated = self.redb_table.update(entity)?;
        event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Customer(EntityEvent::Updated)),
            ids: vec![updated.id.clone()],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_multi(
        &mut self,
        event_hub: &Arc<EventHub>,
        entities: &[Customer],
    ) -> Result<Vec<Customer>, Error> {
        let updated = self.redb_table.update_multi(entities)?;
        event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Customer(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id.clone()).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn delete(&mut self, event_hub: &Arc<EventHub>, id: &EntityId) -> Result<(), Error> {
        let entity = match self.redb_table.get(id)? {
            Some(e) => e,
            None => return Ok(()),
        };
        // get all strong forward relationship fields

        // delete all strong relationships, initiating a cascade delete

        // delete entity
        self.redb_table.delete(id)?;
        event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Customer(EntityEvent::Removed)),
            ids: vec![id.clone()],
            data: None,
        });
        Ok(())
    }

    pub fn delete_multi(
        &mut self,
        event_hub: &Arc<EventHub>,
        ids: &[EntityId],
    ) -> Result<(), Error> {
        let entities = self.redb_table.get_multi(ids)?;
        if entities.is_empty() || entities.iter().all(|e| e.is_none()) {
            return Ok(());
        }

        // get all strong forward relationship fields

        // delete all strong relationships, initiating a cascade delete

        self.redb_table.delete_multi(ids)?;
        event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Customer(EntityEvent::Removed)),
            ids: ids.into(),
            data: None,
        });
        Ok(())
    }
}

pub struct CustomerRepositoryRO<'a> {
    redb_table: Box<dyn CustomerTableRO + 'a>,
}
impl<'a> CustomerRepositoryRO<'a> {
    pub fn new(redb_table: Box<dyn CustomerTableRO + 'a>) -> Self {
        CustomerRepositoryRO { redb_table }
    }
    pub fn get(&self, id: &EntityId) -> Result<Option<Customer>, Error> {
        self.redb_table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Customer>>, Error> {
        self.redb_table.get_multi(ids)
    }
}
